### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by suhanipaliwal** [SB2318/UltimateHealth#10]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me.

**Comment by SB2318** [comment]
Okay, please wait until contributions start.

**Comment by suhanipaliwal** [comment]
The coding period has started so please assign this issue to me. Also, please add labels of GSSOC'24 and appropriate level (like level 1, 2 or 3) on this issue. Thank you.

**Comment by SharmaNishchay** [comment]
Added Code_of_Conduct.md file
