### ISSUE TITLE
💡[FEATURE]: PR Title Checker

### ISSUE THREAD

**Issue by sanmarg** [SB2318/UltimateHealth#101]
Implement a GitHub Actions workflow to automatically validate the titles of pull requests (PRs) when they are opened, edited, reopened, or synchronized. This workflow will ensure that all PR titles adhere to our project's naming conventions, improving clarity and consistency across the repository.

Maintaining a consistent format for PR titles is crucial for effective project management and code review processes. It helps team members quickly understand the purpose and scope of a PR. Automating the validation of PR titles ensures that contributors follow the established naming conventions without manual oversight.

Please assign this issue to me.

**Comment by SB2318** [comment]
Yes, It is necessary. Thanks for opening the issue.

**Comment by sanmarg** [comment]
Could you please upgrade this cause I think is should not be under level 1... It required me to learn some things.

**Comment by SB2318** [comment]
@sanmarg let me know if you have facing any difficulties in the task.

**Comment by Maheshwari-Love** [comment]
@SB2318 can you assign this task to me...

**Comment by SB2318** [comment]
@Maheshwari-Love  If you are a GSSOC contributor and facing any issues in your task, please contact me.

**Comment by suhanipaliwal** [comment]
can you please assign this issue to me?

**Comment by Maheshwari-Love** [comment]
> can you please assign this issue to me?

@suhanipaliwal i am working on this by tomorrow it will be done

**Comment by suhanipaliwal** [comment]
It has been a lot of time since this issue is open and not worked upon. So I'm raising a pull request now.
