### ISSUE TITLE
💡[FEATURE]:  Design HomeScreen

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#113]
### Prototype :

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/1aabae25-6d1a-4830-8b34-948a5325c973)

### Task Area:
 **HomeScreen** (`./frontend/src/screens/HomeScreen`)

### Tasks:

* Implement React Native Tab View, then try to customize it.
For your reference:
(i) https://reactnavigation.org/docs/tab-view/
(ii) https://www.npmjs.com/package/react-native-collapsible-tab-view
* Integrate **FlatList** and try to create **FlatList** data from UI. For all categories, add at least 2 data points for **FlatList.**
* Design **FlatList** Item, Make sure the item UI will be divided into two parts as per Figma; one part will be covered by the image, and the height of the image will be adjusted by the height of its parent container. The other part will contain the information.

Demo Article data for **FlatList** :

article = [
     {
        id:'1',
        title:"The history of Doctor",
        description:"Doctor comes from the Latin word for "teacher" and originally referred to a small group of theologians who had approval from the Church to speak on religious matters."
        content:""
        category:["Stories"],
       author_name:"AuthorName",
       lastUpdatedAt:"24.06.2024",
      imageUtils: "ImageUrl",
    }
]

**Comment by rushiii3** [comment]
Hey @SB2318, i would like to do this task!

**Comment by ParthNakum21** [comment]
Hello @SB2318, I would like to work on this task.
Could you please assign this task to me.
