### ISSUE TITLE
💡[FEATURE]:  Design ProfileScreen UI

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#114]
Prototype:

Due date: 27.06.2024

**Comment by rushiii3** [comment]
Hey @SB2318, i would like to do this task!

**Comment by ParthNakum21** [comment]
Thanks for the assignment! waiting for the prototype, to start working on the issue.

**Comment by meenakshiiyer2531** [comment]
Hey @SB2318,
Can this issue be assigned to me for Gssoc'24
Regards,
V Meenakshi Iyer

**Comment by SB2318** [comment]
@rushiii3 please let me know your availability.

**Comment by rushiii3** [comment]
> @rushiii3 please let me know your availability.

Yes, I am available

**Comment by SB2318** [comment]
> > @rushiii3 please let me know your availability.
> 
> Yes, I am available

Okay this is a new task for you. You have to create a responsive design for profile in figma.
There will be some controlled visibility regarding Doctor and General profile.

And there will be three tabs:

(i) My Articles
(ii) Save Articles
(iii) Activity Overview

Let me know If you want to take the task.

**Comment by rushiii3** [comment]
> > > @rushiii3 please let me know your availability.
> > 
> > 
> > Yes, I am available
> 
> Okay this is a new task for you. You have to create a responsive design for profile in figma. There will be some controlled visibility regarding Doctor and General profile.
> 
> And there will be three tabs:
> 
> (i) My Articles (ii) Save Articles (iii) Activity Overview
> 
> Let me know If you want to take the task.


I don't know much about using Figma, but I'll give it a try. If it doesn't work for me, I'll report back in 2 to 3 days.
Is it fine??

**Comment by SB2318** [comment]
> > > > @rushiii3 please let me know your availability.
> > > 
> > > 
> > > Yes, I am available
> > 
> > 
> > Okay this is a new task for you. You have to create a responsive design for profile in figma. There will be some controlled visibility regarding Doctor and General profile.
> > And there will be three tabs:
> > (i) My Articles (ii) Save Articles (iii) Activity Overview
> > Let me know If you want to take the task.
> 
> I don't know much about using Figma, but I'll give it a try. If it doesn't work for me, I'll report back in 2 to 3 days. Is it fine??

Sure! Start with simple, 
Here is your playground link:  https://www.figma.com/files/team/1388227628794995726/all-projects?fuid=1388227018108034490
