### ISSUE TITLE
💡[FEATURE]:  Sign up page development.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#115]
### Task Description Commit History: 

https://github.com/SB2318/UltimateHealth/commit/097a8a5b453d16c4c1ff47f8f14cda7ec44dc218

### Task Area:

  * ` ./frontend/src/services/AuthApiService.ts`
  * ` ./frontend/src/screens/SignUpScreenFirst.tsx`
  *  `./frontend/src/screens/SignUpScreenSecond.tsx`

**Comment by ParthNakum21** [comment]
Hello @SB2318, I would like to work on this task. 
Could you please assign this task to me under GSSoC with appropriate level?

**Comment by SB2318** [comment]
> Hello @SB2318, I would like to work on this task.  Could you please assign this task to me under GSSoC with appropriate level?

Sure! But please make sure, your all previous tasks are complete on this project.

**Comment by nikita7526** [comment]
Hey! @SB2318  can you please assign this to me under GSSoc, i would like to work on this

**Comment by SB2318** [comment]
@ParthNakum21 any update about ur previous task

**Comment by ParthNakum21** [comment]
> @ParthNakum21 any update about ur previous task

Working on the changes you mentioned in the #132.

**Comment by SB2318** [comment]
> > @ParthNakum21 any update about ur previous task
> 
> Working on the changes you mentioned in the #132.

okay, let me know If any help needed.

**Comment by anjaliyadavks** [comment]
Hello @SB2318
I would love the opportunity to contribute and work on this project.
Could you please assign the issue to me? I'm eager to drive in and make a meaningful impact. Thank you for considering my request!

**Comment by SB2318** [comment]
> Hello @SB2318 I would love the opportunity to contribute and work on this project. Could you please assign the issue to me? I'm eager to drive in and make a meaningful impact. Thank you for considering my request!

Okay, you can start work from tomorrow. 😇

For any queries, mail at: **ultimate.health25@gmail.com**

**Comment by Vinaysohaliya** [comment]
Hello @SB2318 
I would love the opportunity to contribute and work on this project.
Could you please assign the issue to me?

**Comment by SB2318** [comment]
Welcome to GSSOC program 💖💖
Okay 😇, please wait for tomorrow.

**Comment by SB2318** [comment]
Hello @nikita7526! 👋 As a GSSOC contributor, you have received first preference.
Thanks for selecting the repository, you can start work. 😊 You have to handle the Create account feature.
First, please try to run the application. If you need more clarification about your work, please reach out to me.

**Comment by nikita7526** [comment]
okay, I will let you know if needed help.

**Comment by nikita7526** [comment]
> Hello @nikita7526! 👋 As a GSSOC contributor, you have received first preference. Thanks for selecting the repository, you can start work. 😊 You have to handle the Create account feature. First, please try to run the application. If you need more clarification about your work, please reach out to me.

okay, i will let you know if needed help :)

**Comment by i-akii** [comment]
is this issue solved?
If not please assign this to me.

**Comment by SB2318** [comment]
> is this issue solved? If not please assign this to me.

Okay, Let me know if you need any details.
