### ISSUE TITLE
💡[FEATURE]:  ArticleViewPage Design in figma

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#116]
**Is your feature request related to a problem? Please describe.**

The design of the page where the article will be viewed.

**Describe the solution you'd like**

![070414dcd39ea0ab9b43aceca5fb5ec7](https://github.com/SB2318/UltimateHealth/assets/87614560/ce0b67a4-dba1-4986-8c26-8fa18fe45662)

Follow the above UI.

**Describe alternatives you've considered**

Changes:

For Like or love
* Blue Circle(PRIMARY_COLOR) & white love (Not like condition)
* White Circle & Blue((PRIMARY_COLOR) love  (Like Condition)

Change the image with a doctor-article image. specially it will be the image .
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/6ddc416b-1092-4756-b531-71e7998974e3)

You have to set the Click action on those flatlist.

* Categories (In the place of "My story")
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/fd36f430-bf0e-4215-a491-3d99e4613381)

* View Count or viewd by (View count) in the place of
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/ed65b7e3-df06-4e93-9a00-240cbc0481fc)

*  Follow Button Color: PRIMARY_COLOR
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/2a6ab309-4ed5-4820-aab5-1ded0e96091e)

* Use **react-native-webview** for content. and use some dummy html content as of now for rendering.

**Additional context**

* Set Click action of the flatlist item of the home page and send and arrange available data on ArticleViewScreen.

**Comment by MaryamMohamedYahya** [comment]
I am interested in making the view page. Kindly assign this to me under the labels once the prototype is ready.

**Comment by mayghhaa** [comment]
I'm interested in working on this, please assign.

**Comment by SB2318** [comment]
> I am interested in making the view page. Kindly assign this to me under the labels once the prototype is ready.

Prototype will be available by tomorrow. Please let me know your availability.

**Comment by MaryamMohamedYahya** [comment]
Yes, I'm ready to try it out.

**Comment by mayghhaa** [comment]
Yes, i'm available to do it tomorrow.

**Comment by MaryamMohamedYahya** [comment]
Do I fork the develop branch?

**Comment by SB2318** [comment]
> Do I fork the develop branch?

Yes

**Comment by SB2318** [comment]
@MaryamMohamedYahya  please come in the discord channel if you need any guidance related your task.

**Comment by MaryamMohamedYahya** [comment]
Please give the channel name

**Comment by SB2318** [comment]
> Please give the channel name

susmita_5116

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  Hlo i want to work on this i will raise pr on another day surely .
