### ISSUE TITLE
💡[FEATURE]: Check Network Connection & Create a No Internet Layout

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#117]
### Task Description Commit History: 

https://github.com/SB2318/UltimateHealth/commit/d3fa02c237b234fb0ebf6a705a346aed7f003a2e

### Prerequisite Learning:

`useDispatch()` and `useSelector()` hooks.

**Is your feature request related to a problem? Please describe.**

The network connection checks are necessary during API calls, and There is a need for no-internet layout also. Your task is to design a component for "No internet" layout and a utility function that will check the network connectivity so that we can make sure that we are calling API only when the network is available.

**Describe the solution you'd like**

## Task Area:

* Make sure you have add necessary permissions in **AndroidManifest** file.

* .`/frontend/src/components/` 

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/73397199-20ed-44cf-b180-3da5ec713761)

* `./frontend/src/helper/Utils`
 Create a Utils function to check whether the network connection is available.
Additionally add one listener in the top-level app component to identify network connection change, and update redux state value.

* ./frontend/src/screens/HomeScreen.tsx

Test Here

Retrieve network data from the redux store using useSelector()

if( !available) Display No InternetLayout 
else Default Setup

### Click Action :  (Try Again) Button

if( !available) Display No InternetLayout 
else Default Setup

**Additional context**

 **Redux-SetUp**  Done

**Comment by ParthNakum21** [comment]
Hello @SB2318, I would like to work on this task. 
Could you please assign this task to me?

**Comment by Sneha0019** [comment]
Hey, @SB2318 I am interested to work on this issue. I can complete it within a day. Please assign me this under GSSOC'24 contributor

**Comment by SB2318** [comment]
> Hey, @SB2318 I am interested to work on this issue. I can complete it within a day. Please assign me this under GSSOC'24 contributor

Sure, Go for it. Do you need any guidance?

**Comment by Sneha0019** [comment]
Thank you for assigning, if there is any need of guidance i'll surely ask you to guide!

**Comment by SB2318** [comment]
> I won't be able to work on this issue as I am already working on the prior commitments. I understand the importance of this task and regret any inconvenience this may cause.

Okay, No problem.

**Comment by SB2318** [comment]
@ParthNakum21 would you like to work on the issue.

**Comment by ParthNakum21** [comment]
> @ParthNakum21 would you like to work on the issue.

I am ready to start working on this issue. 
Please provide me with guidance on resolving this issue.

**Comment by SB2318** [comment]
@ParthNakum21 please give a quick update.

**Comment by ParthNakum21** [comment]
> @ParthNakum21 please give a quick update.

"No Internet" layout is ready, working on the utility function.

**Comment by SB2318** [comment]
@ParthNakum21  Am really very sorry! But due to your inactive performance, I can't accept your contribution.

Again, Thanks for your time and effort. 😇

**Comment by SB2318** [comment]
Hello @Sneha0019 please let me know If you are available.
