### ISSUE TITLE
💡[FEATURE]:   Select Image or capture image from device and display it on the screen 

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#122]
## Parent : #84 

## Task Area

`./frontend/src/components`

## Task Description:

You will be responsible for design the following component.

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/b670a302-ebec-422c-b02a-a2ede8c1980e)

Make sure you have added the necessary permission in the AndroidManifest file.

Select Image from the device and display a preview on the screen,
Width and height similar to either descriptionBox or HumanBodyMap image

**Comment by Ar7109** [comment]
@SB2318 Please  assign this issue to me under gssoc 2024
