### ISSUE TITLE
💡[FEATURE]:  Integration Of Components: Create ArticleDescriptionScreen

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#123]
## Task Area:

./frontend/src/screens/

## Task Description

Create ArticleDescription Screen.

Complete the rest design.
Implement Text Watcher functionality

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/10d8da2a-26fa-4724-baed-bceba9a61b66)

Give Validation for each field.

Add it to StackNavigation, and Design the screen  as per UI and with above components. (NoteIcon Click Action)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/1b3656af-b95e-4f15-a3ed-5ed5c64236ef)

**Comment by akjain1509** [comment]
Hello @SB2318 ,
I'm eager to contribute to GSSOC'24 by working on this Integration Of Components: Create ArticleDescriptionScreen issue. Please assign it to me. I'll enhance the app display and a user-friendly UI. Directory:./frontend/src/screens/.

**Comment by divyesh-mali** [comment]
Please assign me this issue. I would like to work on it.
