### ISSUE TITLE
💡[FEATURE]:  Create Custom Dropdown Component.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#124]
Reference: https://blog.logrocket.com/creating-custom-react-native-dropdown/

### Task Area:

./src/frontend/components/

### Tasks:

* Received an array argument in your component and  or create an array.
* Conditionally visible an listview based on drop up and drop down
* Display one modal on the click action of Add New
* Add the new item in the array

**Comment by akjain1509** [comment]
Hello @SB2318  mam. I would like to work on this feature. Kindly assign me this task.

**Comment by amanjaiswal7236** [comment]
Hey @SB2318 , I would like to work on this feature . Can u please assign it to me under GSSOC'24.

**Comment by rushiii3** [comment]
@SB2318, can i work on this?

**Comment by SB2318** [comment]
@rushiii3  there is a little bit change in the requirement.
From admin part we are going to post thos specializations. 
So, you don't need to add the **plus** part in the dropdown.

But, you have to design the Custom Dropdown component  relevant to app theme.

You can use **react-native-select-dropdown**, I think they provide some customisation options also. 😇
Feel free to apply your own creativity.
