### ISSUE TITLE
💡[FEATURE]:  Create Tags or Article Categories API.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#125]
So, Here you will be responsible for creating article categories api.

FrontEnd Part:

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/56ae47ec-26f5-436d-b316-44d653d7513c)

You have to make the backend:

Create ArticleController, and implement the 4 CRUD operations (Post, Get, Update, Delete)
 Test them and commit your changes.

### Task Area: 
Backend

schema:{
       id: string/number,
      name: string,
}

**Comment by nishant0708** [comment]
hey can i work on this?

**Comment by nishant0708** [comment]
hey @SB2318 can you clear me few things we have two types of tags write one which are predefined these 
![image](https://github.com/SB2318/UltimateHealth/assets/101548649/d76aa506-059a-4ce6-b89d-1a613aca6708)
and which user Can Add right ??  or this image consist of tag user have and 

in schema 

id: string/number, this is Tag Id right ? or User Id .


how you Want me to Store Tags In array set or something Else...

**Comment by SB2318** [comment]
> hey @SB2318 can you clear me few things we have two types of tags write one which are predefined these ![image](https://private-user-images.githubusercontent.com/101548649/339966573-d76aa506-059a-4ce6-b89d-1a613aca6708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDA1MDksIm5iZiI6MTcxODQ0MDIwOSwicGF0aCI6Ii8xMDE1NDg2NDkvMzM5OTY2NTczLWQ3NmFhNTA2LTA1OWEtNGNlNi1iODlkLTFhNjEzYWNhNjcwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwODMwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjI5NjYzNTk0MDM4NzdiYjM0NjQ1YjQ5ODEyOWRhZjRmY2Q1OWViMmNjM2RhOGIzZTk2Yjg1ZDQwYWE0YWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u0n-fTsocAPTtNCrdWIEDtuqlNu76eIENa8a6yrTJTg) and which user Can Add right ?? or this image consist of tag user have and
> 
> in schema
> 
> id: string/number, this is Tag Id right ? or User Id .
> 
> how you Want me to Store Tags In array set or something Else...

no, all tags will be come from api. This '+' sign indicate you want the particular tag with your article.
