### ISSUE TITLE
💡[FEATURE]: Automatic Comment on Pull Request Raised

### ISSUE THREAD

**Issue by thevijayshankersharma** [SB2318/UltimateHealth#126]
**Is your feature request related to a problem? Please describe:**
Pull requests (PRs) are an integral part of collaborative development workflows. However, sometimes the significance of a PR or its context may not be immediately apparent to reviewers. This lack of context can lead to misunderstandings or delays in the review process.

**Describe the solution you'd like:**
I would like to see an automatic comment feature implemented that triggers whenever a new pull request is raised. This comment would provide essential context about the changes proposed in the PR, including details such as the purpose of the changes, any relevant issue or feature IDs, and any specific instructions for reviewers.

**Describe alternatives you've considered:**
One alternative could be manually adding context to each PR description. However, this approach is prone to oversight and may not be consistently applied across all PRs. Another option could be relying solely on the PR title or commit messages for context, but these may not always convey the full scope or intent of the changes.

**Additional context:**
Having an automatic comment added to each newly raised PR would streamline the review process by ensuring that reviewers have all the necessary information upfront, reducing the need for back-and-forth clarification. Additionally, it would improve transparency and accountability within the development team by documenting the rationale behind each set of changes.

**Comment by SB2318** [comment]
There are already auto-commenting features that exist for first-time contributors.  Let me know what will be your message description in your case.

**Comment by thevijayshankersharma** [comment]
As of now in your repo you have same message for both issue and PR. i would like to change the message for PR to something like this :
Thank you @name ,for creating the PR and contributing to our UltimateHealth💗
Review team will review the PR and will reach out to you soon! 😇
Make sure that you have marked all the tasks that you are done with ✅.
Thank you for your patience! 😀

and if you need i can add other workflows like closing the old issues or PR, or labeling it.

**Comment by SB2318** [comment]
> As of now in your repo you have same message for both issue and PR. i would like to change the message for PR to something like this : Thank you @name ,for creating the PR and contributing to our UltimateHealth project💗 Our team will review the PR and will reach out to you soon! 😇 Make sure that you have marked all the tasks that you are done with ✅. Thank you for your patience! 😀
> 
> and if you need i can add other workflows like closing the old issues or PR, or labeling it.

Make sure that, no existing feature will be lost. 😇

**Comment by SB2318** [comment]
> As of now in your repo you have same message for both issue and PR. i would like to change the message for PR to something like this : Thank you @name ,for creating the PR and contributing to our UltimateHealth project💗 Our team will review the PR and will reach out to you soon! 😇 Make sure that you have marked all the tasks that you are done with ✅. Thank you for your patience! 😀
> 
> and if you need i can add other workflows like closing the old issues or PR, or labeling it.

No need to close old issues or PR as of now Because The issues are already optimized way, If we do so we may miss some important points.
 Thanks for raising an issue on the assigned feature.
 Let me aware if you need any help regarding this.
