### ISSUE TITLE
💡[Feature]: Redirect User to home page After  Verification 

### ISSUE THREAD

**Issue by nishant0708** [SB2318/UltimateHealth#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently when user verifies his account he get redirected to registration page instead of that we can send him directly to home page. and As Soon as he click on the mail to verify his account he will recieve response Mail of User Email Verified Successfully.
And Can Navigate to Home page 

### Use Case

It will make app easy to use for user

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

Prepare an analysis and share it via mail or in discord respective project channel.

**Comment by SB2318** [comment]
@nishant0708  You have to work  on the backend, I will give the frontend functionality,

Send Verification Email:

Construct the verification email content with clear instructions on how to verify the email address.
Include the deep link with the verification token embedded within it (e.g., https://yourapp.com/verify?token=YOUR_VERIFICATION_TOKEN).
Use a secure and reputable email service provider (ESP) to send the verification email.
Handle Deep Link Click (Backend):

When the user clicks the verification link in the email, your backend will receive a request containing the deep link.
Extract the verification token from the deep link.
Validate the token by checking the database for a matching token associated with the user's email address and ensuring it hasn't expired.
If the token is valid, update the user's account status to "verified" in the database.

**If you want to automatically log the user in after successful verification:**

Sign a JSON Web Token (JWT) containing the user's ID and other necessary information upon successful verification.
Include the JWT in the response to the deep link click request. (When the user clicks the verification link in the email, your backend will receive a request containing the deep link.)

The mobile app frontend will handle the JWT for subsequent authenticated API calls.

Deep Link Handling Flow:

User Clicks Verification Link in Email:

Clicking the verification link in the email containing the deep link URL (e.g., yourapp://verify?token=YOUR_VERIFICATION_TOKEN) will initiate one of two scenarios:
**App Installed:** If the user's device has your app installed and configured with the custom URL scheme, the deep link will be handled directly by your app.
**App Not Installed:** If the app is not installed, the user's device will typically redirect them to your app's page in the Play Store (or the App Store for iOS).

Deep Link Received by App (if app is installed):

Assuming the app is installed and configured with the custom URL scheme, the operating system will attempt to open your app using the deep link.
Your app's deep link handler, typically implemented using a library or framework like Branch, Firebase Dynamic Links, or Universal Links, will intercept this deep link.
Deep Link Handler Extracts Token:

The deep link handler will parse the received deep link URL and extract the verification token embedded within it (e.g., the token parameter in the example URL).
Verification and Login Process (as described previously):

The app will then proceed with the verification and login process as outlined in the previous section:
Validate the extracted token against your backend server to ensure its authenticity and validity.
Optionally, handle automatic login using a JWT (if implemented).
Update the user's account status to "verified" if successful.
Provide the user with a success message or automatically log them in.
Key Points:

The deep link handler's role is to intercept the incoming deep link URL and extract the verification token for further processing.
The verification and login flow will be handled as described, ensuring the user's account is verified upon successful token validation.

This is my analysis, please prepare your analysis first and send it to me before you assign the work.

**Comment by nishant0708** [comment]
Hey @SB2318 I checked Code and The backend currently  is performing Same Functionality ..Just  we need a page where we can add text Like 
Welcome to Ultimate Health
your are Verified Successfully
_____________________________
|     Open  App                    |                              <---------This Button On Click will open App
|____________________________|_

**Comment by SB2318** [comment]
> Hey @SB2318 I checked Code and The backend currently is performing Same Functionality ..Just we need a page where we can add text Like Welcome to Ultimate Health your are Verified Successfully
> 
> ```
> _____________________________
> |     Open  App                    |                              <---------This Button On Click will open App
> |____________________________|_
> ```

no it doesn't open the app after email verification automatically. 
Only showing a success message.

**Comment by nishant0708** [comment]
No I am asking should I make it like this ?

**Comment by SB2318** [comment]
> > Hey @SB2318 I checked Code and The backend currently is performing Same Functionality ..Just we need a page where we can add text Like Welcome to Ultimate Health your are Verified Successfully
> > ```
> > _____________________________
> > |     Open  App                    |                              <---------This Button On Click will open App
> > |____________________________|_
> > ```
> 
Yes you are right.
It means you want to add a button with success message.

will discuss
