### ISSUE TITLE
Create Application Logo

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#14]
**Color:** 

 **PRIMARY_COLOR** ="#0CAFFF"
 **ON_PRIMARY_COLOR** = "#FFFFFF"
 **SECONDARY_COLOR** ="#00BFFF"
 
 Description:
 
 Welcome to all contributors🎉.
 
 Let's start our journey with a beautiful game.
 
 This issue will not be first come first serve basis, you all are welcome to take part in this challenge.
 
 The task will be, Please design a suitable logo for the application. (Color code mentioned above).
 
 At the end of the day mentor will give you the feedback. She will select the appropriate logo for our project.

Leave a comment here and start your work. (Only If, you are interested)
 
 Keep Contributing!

**Comment by BHS-Harish** [comment]
Hello @SB2318 

I created the minimalistic logo for your project Ultimate Health with given color code.

## Meaning of the logo
- The background symbol "U" indicate the word "Ultimate"
- The inner heart symbol indicates the word "Health"

The logo mentioned below
## Light Mode
![Ultimate Health-light](https://github.com/SB2318/UltimateHealth/assets/114602603/f3d12ef1-7678-40c0-acd8-929c8d8bfa19)
## Dark Mode
![Ultimate Health-dark](https://github.com/SB2318/UltimateHealth/assets/114602603/c8a0892a-0eae-4bbf-bf9a-6d86113fc438)


Waiting for your valuable comments.
Please assign the issue to me

Thanks in advance.

**Comment by KavyaBS123** [comment]
Hey @SB2318 I am a GSSOC contributor can you please assign this issue to me I would love to work on it!

**Comment by AnushkaSharma04** [comment]
hey @SB2318 I am a gssoc'24 contributor . Can you assign this issue to me

**Comment by SB2318** [comment]
> Hello @SB2318
> 
> I created the minimalistic logo for your project Ultimate Health with given color code.
> 
> ## Meaning of the logo
> * The background symbol "U" indicate the word "Ultimate"
> * The inner heart symbol indicates the word "Health"
> 
> The logo mentioned below
> 
> ## Light Mode
> ![Ultimate Health-light](https://private-user-images.githubusercontent.com/114602603/329810553-f3d12ef1-7678-40c0-acd8-929c8d8bfa19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDk5MTMsIm5iZiI6MTcxNTUwOTYxMywicGF0aCI6Ii8xMTQ2MDI2MDMvMzI5ODEwNTUzLWYzZDEyZWYxLTc2NzgtNDBjMC1hY2Q4LTkyOWM4ZDhiZmExOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMDI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2NkZTEyMTVlOWI0OWVmZDAzOGQ3YTQ2NWFjM2QzNDkwZjhhNTQwZGY0ZjlmYmMxMzU3NzZiMzIzYmY0Mjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WrDCmasPjztBv3Vo3pAr7OVNy8mahC8BN0hlrZmClcQ)
> 
> ## Dark Mode
> ![Ultimate Health-dark](https://private-user-images.githubusercontent.com/114602603/329810570-c8a0892a-0eae-4bbf-bf9a-6d86113fc438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDk5MTMsIm5iZiI6MTcxNTUwOTYxMywicGF0aCI6Ii8xMTQ2MDI2MDMvMzI5ODEwNTcwLWM4YTA4OTJhLTBlYWUtNGJiZi1iZjlhLTZkODYxMTNmYzQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMDI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTNmY2QxYjUzYWNhY2M2NzgyOWMwNjIyOGJiYjAxMGY5MDlhNjZmNjdlNDcxNGZiZDM2MTAwNjNjNzEzMmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C7fL2e4vtX-Je8oJ5P2Vm_Btbgs10oZVCRQZVhl6aJk)
> 
> Waiting for your valuable comments. Please assign the issue to me
> 
> Thanks in advance.

Looks Good! Great Work 🎉

**Comment by SB2318** [comment]
> Hey @SB2318 I am a GSSOC contributor can you please assign this issue to me I would love to work on it!

You are welcome to give it a try!

**Comment by SB2318** [comment]
> hey @SB2318 I am a gssoc'24 contributor . Can you assign this issue to me

You are welcome to give it a try!

**Comment by BHS-Harish** [comment]
> > Hello @SB2318
> > I created the minimalistic logo for your project Ultimate Health with given color code.
> > ## Meaning of the logo
> > 
> > * The background symbol "U" indicate the word "Ultimate"
> > * The inner heart symbol indicates the word "Health"
> > 
> > The logo mentioned below
> > ## Light Mode
> > ![Ultimate Health-light](https://private-user-images.githubusercontent.com/114602603/329810553-f3d12ef1-7678-40c0-acd8-929c8d8bfa19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDk5MTMsIm5iZiI6MTcxNTUwOTYxMywicGF0aCI6Ii8xMTQ2MDI2MDMvMzI5ODEwNTUzLWYzZDEyZWYxLTc2NzgtNDBjMC1hY2Q4LTkyOWM4ZDhiZmExOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMDI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2NkZTEyMTVlOWI0OWVmZDAzOGQ3YTQ2NWFjM2QzNDkwZjhhNTQwZGY0ZjlmYmMxMzU3NzZiMzIzYmY0Mjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WrDCmasPjztBv3Vo3pAr7OVNy8mahC8BN0hlrZmClcQ)
> > ## Dark Mode
> > ![Ultimate Health-dark](https://private-user-images.githubusercontent.com/114602603/329810570-c8a0892a-0eae-4bbf-bf9a-6d86113fc438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDk5MTMsIm5iZiI6MTcxNTUwOTYxMywicGF0aCI6Ii8xMTQ2MDI2MDMvMzI5ODEwNTcwLWM4YTA4OTJhLTBlYWUtNGJiZi1iZjlhLTZkODYxMTNmYzQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMDI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTNmY2QxYjUzYWNhY2M2NzgyOWMwNjIyOGJiYjAxMGY5MDlhNjZmNjdlNDcxNGZiZDM2MTAwNjNjNzEzMmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C7fL2e4vtX-Je8oJ5P2Vm_Btbgs10oZVCRQZVhl6aJk)
> > Waiting for your valuable comments. Please assign the issue to me
> > Thanks in advance.
> 
> Looks Good! Great Work 🎉

Thank you @SB2318

**Comment by SB2318** [comment]
[@BHS-Harish](https://github.com/BHS-Harish) Please check the frontend folder (check the readme file)

Inside the **src** folder **(./project/src)** create a new folder named **assets**.

keep your assets there and make a PR by mentioning this issue.

Keep contributing!
