### ISSUE TITLE
💡[Feature]: Conditionally display a VerifyEmail Button and connect it with backend , If you get for specific response.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Task Area:

**LoginPage**

What you have to do, 
When you click login button, then this function will be called,

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/2bcbcfc0-70a9-48a8-a8f2-89d5eeb77896)

After collecting the response from API, if you get this type of response:

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/942f0d58-1eb5-4c46-8433-029e97d82f72)

Display a verify email button, instead of moving, to store data

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/7afa560d-c6fa-4ec2-95db-f34c8ed39206)

And on verify email click add its functionality.

### Use Case

Later

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Gsha36** [comment]
Hi @SB2318 I am a GSSoC'24 contributor. How is the progress with this task? I would like to work on this issue.

**Comment by SB2318** [comment]
> Hi @SB2318 I am a GSSoC'24 contributor. How is the progress with this task? I would like to work on this issue.

Message on project channel, If you need any help.

**Comment by Gsha36** [comment]
Hi Susmita, thank you for assigning me this issue. I will get back to you
with updates. Could you tell me what do you mean by project channel?

**Comment by SB2318** [comment]
Are you a GSSOC contributor?

**Comment by komalverma04** [comment]
@SB2318 I am interested to work on this issue, if it is available please assign it to me so that i can start the work.

**Comment by SB2318** [comment]
> @SB2318 I am interested to work on this issue, if it is available please assign it to me so that i can start the work.

Okay will assign you.

**Comment by SB2318** [comment]
**Request Verification** added
