### ISSUE TITLE
📝[Docs]:  Can a cancer patient live a normal life?

### ISSUE THREAD

**Issue by ananyag309** [SB2318/UltimateHealth#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

You have to prepare an analysis for the following topics in a markdown file.

### Can a cancer patient live a normal life?

(i) How different is their life from the daily life of an ordinary person?
(ii) How much extra care and attention they needed.
(iii) Their trauma, anxiety, depression, and their solutions, How they can keep their mind fresh.
(iv) Is cancer genetic?
(v) Is cancer contagious?
 

### Suggested Change

I would like to make it more well organise. If needed please assign this issue to me.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@ananyag309 Please let me know whether you are available for the issue.

**Comment by ananyag309** [comment]
@SB2318 please add my name under assignes so that i can start working on it

**Comment by ananyag309** [comment]
@SB2318 Do i need to create that md file in a particular folder ? with what name should i create it

**Comment by SB2318** [comment]
> @SB2318 Do i need to create that md file in a particular folder ? with what name should i create it

https://github.com/SB2318/UltimateHealth/tree/develop/DataSources

Here you have to add your MD file.
