### ISSUE TITLE
📝[Docs]:  Which is more dangerous, diabetes mellitus or insipidus?

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

(i) Diabetes mellitus vs Diabetes insipidus -> What you should know.
(ii) Types of Diabetes
(iii) Medicine
(iv) Ideal  Lifestyle and precautions for a diabetic patient, (If possible, prepare a diet chart).
(v) How this disease affects health in the worst case.

### Suggested Change

Prepare a markdown file

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Aditijainnn** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Issue Description
> 
> (i) Diabetes mellitus vs Diabetes insipidus -> What you should know. (ii) Types of Diabetes (iii) Medicine (iv) Ideal Lifestyle and precautions for a diabetic patient, (If possible, prepare a diet chart). (v) How this disease affects health in the worst case.
> ### Suggested Change
> 
> Prepare a markdown file
> ### Rationale
> 
> _No response_
> ### Urgency
> 
> Medium
> ### Record
> 
>     * [x]  I have read the Contributing Guidelines
> 
>     * [ ]  I'm a GSSOC'24 contributor
> 
>     * [ ]  I want to work on this issue

please assign this to me under GSSoc'24
