### ISSUE TITLE
📝[Docs]:  Caring for children with disabilities

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

A disability is any condition of the body or mind (impairment) that makes it more difficult for the person with the condition to do certain activities (activity limitation) and interact with the world around them (participation restrictions).

Some disabilities are congenital, And some accidents.  
You have to write this article - **The article on congenital disability**

### Introductions: 
Understanding Disabilities 
Select any three disabilities  (deaf, born blind, lack of mental growth) 
You have to explore those, and have to provide your insights and analysis on the following sections:
(i) Needs of Creating a Supportive Environment:
(ii) Their Education and Learning:
(iii) Communication and Interaction with them
(iv) Their as well as their parents physical and emotional wellbeing
(v) Access to Healthcare and services
(vi) Resources and supports
At last you have to cover the sections:
Promoting Inclusion and Awareness:

(vii) Include those organizations' website links who are currently working on the project.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nishant0708** [comment]
Assign me this

**Comment by akshathere** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Issue Solution
> I have read the docs about Congential disability from various trusted resources and I think I am capable of writing this article on congenital disability 

> One of the website that I am using for reading about this is 
> https://www.who.int/health-topics/congenital-anomalies#tab=tab_1
> This is official WHO website

> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x ]  I'm a GSSOC'24 contributor
> * [ x]  I want to work on this issue

**Comment by SB2318** [comment]
> > ### Is there an existing issue for this?
> > 
> > * [x]   I have searched the existing issues
> > 
> > ### Issue Solution
> > I have read the docs about Congential disability from various trusted resources and I think I am capable of writing this article on congenital disability
> 
> > One of the website that I am using for reading about this is
> > https://www.who.int/health-topics/congenital-anomalies#tab=tab_1
> > This is official WHO website
> 
> > ### Record
> > 
> > * [x]   I have read the Contributing Guidelines
> > * [x]   I'm a GSSOC'24 contributor
> > * [x]   I want to work on this issue
> 
> Please assign this to me under GSSoc'24. I would love to work on this issue Thanks and waiting for your reply

sure! you can start.

**Comment by akshathere** [comment]
@SB2318  mam I have some doubts regarding this 
Can we connect on discord or on some other platforms

**Comment by SB2318** [comment]
> @SB2318 mam I have some doubts regarding this Can we connect on discord or on some other platforms

Ya! sure, we can connect on those times I have mentioned in the channel, Let me know your availability there.

**Comment by akshathere** [comment]
sorry to ask but I am unable to find the channel
Can you please share it.

**Comment by SB2318** [comment]
> sorry to ask but I am unable to find the channel mam Can you please share it.

You ping me or share your discord id.

**Comment by akshathere** [comment]
unstoppable_av #2425
