### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by SharmaNishchay** [SB2318/UltimateHealth#15]
Add MIT LICENSE to the project

**Comment by AnushkaSharma04** [comment]
Kindly assign this issue to me . I am a gssoc'24 contributor

**Comment by SharmaNishchay** [comment]
> Kindly assign this issue to me . I am a gssoc'24 contributor

@AnushkaSharma04, the issue has been resolved, and merging the pull request will finalize the fix. Could you kindly shift your attention to another issue that still needs to be addressed?
