### ISSUE TITLE
💡[Feature]: Design Profile Frontend.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Figma Link: https://www.figma.com/design/8SUe3fgCpIvBIkXHbLoI7D/UltimateHealth?node-id=0-1&t=zPJSjBPX3y2s6dRb-1

### Use Case

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@rushiii3 let me know your availability.

**Comment by rushiii3** [comment]
Yes, I am available. You can assign me this task!

**Comment by SB2318** [comment]
@rushiii3 any update?

**Comment by rushiii3** [comment]
Its ready, but facing some issues for iOS

**Comment by SB2318** [comment]
> Its ready, but facing some issues for iOS

okay, let me know if you  need any help.

**Comment by SB2318** [comment]
@rushiii3 any update?

**Comment by rushiii3** [comment]
@SB2318 check discord

**Comment by SB2318** [comment]
> @SB2318 check discord

Nice work! Make the neccessary changes and create your PR.
