### ISSUE TITLE
💡[Feature]: Design EditProfile UI

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Design EditProfile UI

### Use Case

NA

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

## Figma access will be provided.

**Comment by akshathere** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Design EditProfile UI
> 
> ### Use Case
> NA
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> Medium
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue
> 
> ## Figma access will be provided.

@SB2318 Can you please assign this issue to me

**Comment by SB2318** [comment]
@akshathere do you want to take this issue, instead of article?

**Comment by akshathere** [comment]
No No, I can do both one by one

**Comment by SB2318** [comment]
1. 

> No No, I can do both one by one

Okay complete your first task.

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  If this is up for grabs i want to work on that

**Comment by SB2318** [comment]
@akshathere are you available for this task?

**Comment by akshathere** [comment]
yes mam

**Comment by akshathere** [comment]
I'm extremely sorry mam I cannot do this task 
It involves react native.
I misunderstood the assignment.
I am unassigning myself
sorry for the inconvenience

**Comment by SB2318** [comment]
@rushiii3 do you want to take this task?

**Comment by rushiii3** [comment]
@SB2318, Sure

**Comment by rushiii3** [comment]
@SB2318, Check if you need any changes. #229
