### ISSUE TITLE
📝[Docs]: Worst Epidemic in India Since 1900's 

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Here in the issue, It is mentioned that **Worst Epidemic in India since 1900's**.

So, This work will be a little bit long.  In this section, you need to provide a brief description of its origin & symptoms, its effects on society, the development of medicine to combat it, and any long-term health effects observed in subsequent pandemics.
And lastly the precautions, 

For your reference:

https://www.jagranjosh.com/general-knowledge/history-of-epidemics-in-india-since-the-1900s-1584627562-1

But you have to collect more details.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by ananyag309** [comment]
can I contribute to this article?

**Comment by SB2318** [comment]
@ananyag309 Please let me know your availability.

**Comment by ananyag309** [comment]
@SB2318 yes, i am ready to complete this issue. Please assign it to me

**Comment by SB2318** [comment]
@ananyag309 any update?

**Comment by ananyag309** [comment]
on it, it will be done till tomorrow, i have taken all symptoms and precautions from ai that's why it is taking time to remove plagiarism,

**Comment by SB2318** [comment]
> on it, it will be done till tomorrow, i have taken all symptoms and precautions from ai that's why it is taking time to remove plagiarism,

Ya sure! you can take your time.
