### ISSUE TITLE
💡[Feature]: Fix Bottom Nav Error,

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Error Description will be available by today

### Use Case

Current Behaviour:

![WhatsApp Image 2024-07-12 at 11 38 43 AM](https://github.com/user-attachments/assets/1b199ceb-a9fd-42b5-a27c-1deb20ac27fe)

Expected Feature:

https://github.com/user-attachments/assets/fe2d89a3-9ecd-47a2-bf62-57e05629abc1

* Remove Search section from HomePage, Add it in the bottom nav.

  * On click create the interface.
  *  Add Recent Search items
  * Remove "Event Happening Now" and in this section add this sections:
  
  
![image](https://github.com/user-attachments/assets/09753c21-7820-4ef6-b448-b58b2f9e8af1)

Explore articles.
Get Categories from API. and display here.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SumitDwivedi24X** [comment]
hey, @SB2318 Can you please assign this issue to me i am available for the tasks right now

**Comment by SB2318** [comment]
Okay, issue will available by tomorrow morning. 😇

**Comment by SB2318** [comment]
@SumitDwivedi24X  If you don't get it let me know, and also let me know your availability for the task.

**Comment by SumitDwivedi24X** [comment]
Hey @SB2318 , I understand the issue here, but it's a bit advanced for me, so I won't be able to contribute to this. I'll definitely check out the other issues, though.

**Comment by SB2318** [comment]
> Hey @SB2318 , I understand the issue here, but it's a bit advanced for me, so I won't be able to contribute to this. I'll definitely check out the other issues, though.

Okay 😇
