### ISSUE TITLE
💡[Feature]: Article API creation

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

CRUD Method  (GET, POST, UPDATE, DELETE)

You will responsible for two issues in our repo. (Article Schema preparation as well as CRUD method) 

### Use Case

Article Backend

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nishant0708** [comment]
hey if it is a backend task(only) then assign me this issue

**Comment by SB2318** [comment]
> hey if it is a backend task(only) then assign me this issue

You have to first complete the #57 , 
Let me know whether you are available or not.

**Comment by nishant0708** [comment]
Yaaa assign me

**Comment by nishant0708** [comment]
I am available for both you could assign me both of them

**Comment by SB2318** [comment]
Okay, please complete the first issue.
