### ISSUE TITLE
💡[Feature]: Structure the code  for HomeScreen

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

* You have to separate the style part from screen (Create another file or folder named styles)
* If needed, Keep it simple, but make the code readable.
* Separate  top tab navigator.
    Use the library
     https://www.npmjs.com/package/@react-navigation/material-top-tabs

### Use Case

Code Structure
Make sure every line of code is proper structured and readable.

### Benefits

Readability Increase, So others can contribute easily

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  I want to work on that

**Comment by SB2318** [comment]
@Ayushmaanagarwal1211, would you like to take on this task or proceed with the edit profile user interface?

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  I want to take this task first

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  Sorry for the inconvenience actually i thought that this project is created through react or next js but its a  react native project i don't have proper experience on react native to work on it i am unassigning me you can please assign this to anyone else

I will surely work on backend that is based on the express js so I can work on it easily 
Hope you understand thank u

**Comment by SB2318** [comment]
Okay, don't worry, u can take a look other available issues. 😇

**Comment by rushiii3** [comment]
You can assign me this task!

**Comment by SB2318** [comment]
> You can assign me this task!

Please complete your assigned task.
