### ISSUE TITLE
💡[Feature]: Filter Page Design In figma

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/f19b4b5a-814f-4de4-9d2b-5d1c5c3ed71a)

Follow the UI.

### Please note that we are working on a different application, so the use-case will be adjusted accordingly.

Keep Only date and category in the first page.

### Use Case

Description will be available soon.

### Benefits

Filter page is necessary to filter the articles.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nishant0708** [comment]
Hey @SB2318 can you elaborate what we have to do in this issue

**Comment by SB2318** [comment]
Okay, will do, today first go through by your own.
Share your observation.
You have already contributed article part.

**Comment by samr874** [comment]
Are the contributions still active for this project?

**Comment by SB2318** [comment]
Yes, it is.

**Comment by SB2318** [comment]
@nishant0708 or @samr874  do you want to contribute in it?

**Comment by nishant0708** [comment]
Hey @SB2318 do you want similar figma design for it or you want to make filter section?

**Comment by SB2318** [comment]
> Hey @SB2318 do you want similar figma design for it or you want to make filter section?

Sorry, I can't get. Please give some more details.

**Comment by nishant0708** [comment]
Just asking is it a frontend task ?

**Comment by SB2318** [comment]
> Just asking is it a frontend task ?

@nishant0708 let me clear one thing, until you visualize your frontend, you can't create the proper and useful backend. As you are assigned for article backend, so I will suggest you to take the issue. 😇 It is under UI-UX.  You have to design in figma.

**Comment by nishant0708** [comment]
> > Just asking is it a frontend task ?
> 
> @nishant0708 let me clear one thing, until you visualize your frontend, you can't create the proper and useful backend. As you are assigned for article backend, so I will suggest you to take the issue. 😇 It is under UI-UX. You have to design in figma.
> 
> With a proper understanding of the things, you will automatically transform into a FullStack Developer by mind. 😇

Actually @SB2318 I have no issues to work on this issue but the problem and main problem is my pc is not configured for native and to set it up is causing some issues . So that's why I asked is it a task related to create a figma design or its a frontend task .. So if it is a just a task to create Figma design i would love to work on this issue

**Comment by SB2318** [comment]
Yes, it is figma design.

**Comment by samr874** [comment]
> @nishant0708 or @samr874 do you want to contribute in it?

Hey surely I would contribute to this mobile app design I am a React Native developer with one year of experience . I can help you with this ??

**Comment by SB2318** [comment]
@nishant0708 any update?

**Comment by nishant0708** [comment]
Mam let @samr874 take it because I have not started it and it will take me time

**Comment by SB2318** [comment]
@samr874  how much minimum time you need to complete it?

**Comment by samr874** [comment]
@SB2318 Mam If we are required to redesign the complete UI for application then will take one week of timeline .

**Comment by SB2318** [comment]
> @SB2318 Mam If we are required to redesign the complete UI for application then will take one week of timeline .

No no, You have to design only this particular page.  you have to follow the given design pattern and instruction.

**Comment by samr874** [comment]
@SB2318 will you tell me descriptively about the requirements? interms of tasklist please ? so that I can get idea about what to develop? I am a developer designing Is some thing which I cant deliver ?

**Comment by samr874** [comment]
@SB2318 you can disscuss about the additional features to add into this application ?

**Comment by SB2318** [comment]
> @SB2318 you can disscuss about the additional features to add into this application ?

Go to HomeScreen
Set Click Action on filter page.
On click display a modal, and set up the UI.

Challenges:
(i) Made Upper part transparent & Lower part a white card.
(ii) Take first design part, till Category, Replace view all with reset,

Now, attach this part.

![image](https://github.com/user-attachments/assets/2afbd810-25d8-4956-893a-2d76968ccfda)

**Comment by SB2318** [comment]
> > @SB2318 you can disscuss about the additional features to add into this application ?
> 
> Go to HomeScreen Set Click Action on filter page. On click display a modal, and set up the UI.
> 
> Challenges: (i) Made Upper part transparent & Lower part a white card. (ii) Take first design part, till Category, Replace view all with reset,
> 
> Now, attach this part.
> 
> ![image](https://private-user-images.githubusercontent.com/87614560/349022820-2afbd810-25d8-4956-893a-2d76968ccfda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjE4OTgsIm5iZiI6MTcyMTEyMTU5OCwicGF0aCI6Ii84NzYxNDU2MC8zNDkwMjI4MjAtMmFmYmQ4MTAtMjVkOC00OTU2LTg5M2EtMmQ3Njk2OGNjZmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA5MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNGY0M2VmNjJmNzExZDNjODdlMjhmOGZjOGU3M2UyNWM5ZjFiMGI0ODUyMjIwYTI2YTNmYjZiOGVhOWIwMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2EpTfFgflYjkqaLjp-SXhCbQKjRRugIBXEcJrOhLbC8)

for more info, please connect in discord.

**Comment by SB2318** [comment]
> Noted @SB2318 please share the discord link?

https://discord.com/channels/1231112132595028008/1239802060015276063

**Comment by SB2318** [comment]
@samr874  any update?

**Comment by samr874** [comment]
I am working on developing the UI will need  4 days additionally ?

**Comment by SB2318** [comment]
@samr874 your 4 days over, give me an update or please unassign yourself.

**Comment by rushiii3** [comment]
@SB2318, can I try?

**Comment by SB2318** [comment]
> @SB2318, can I try?

Sure!

**Comment by rushiii3** [comment]
@SB2318 , Check the PR; if changes are needed, please let me know.
