### ISSUE TITLE
📝[Docs]: Robot Assisted Knee Joint Replacement Surgery

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Reference:

(i) https://www.pennmedicine.org/for-patients-and-visitors/find-a-program-or-service/orthopaedics/knee-pain/knee-surgery/knee-replacement-surgery/robotic-knee-replacements

(ii) https://www.lifespan.org/lifespan-living/robotic-knee-replacement-surgery-right-you

(iii) https://www.orthobethesda.com/blog/robotic-vs-traditional-knee-replacement-surgery/

### Suggested Change

Mentioned above

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nishant0708** [comment]
Hey I can work on this

**Comment by AsmitaMishra24** [comment]
@SB2318, I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by SB2318** [comment]
@AsmitaMishra24 don't publish your content anywhere until your PR being merged.
Because, later our application will faces copyright issues.
I hope you will understand. 😌

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 don't publish your content anywhere until your PR being merged. Because, later our application will faces copyright issues. I hope you will understand. 😌

Sure ma'am, also thanks for assigning the issue @SB2318

**Comment by nishant0708** [comment]
Hey @SB2318 is someone working on this ?  Can I work on this

**Comment by SB2318** [comment]
@AsmitaMishra24  any update?

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 any update?

@SB2318, ma'am my end sem exams are going on.....I will complete this by tomorrow's EOD.
