### ISSUE TITLE
💡[Feature]:  Read Article Page frontend dev

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Links to the work
Design - https://www.figma.com/design/TNmgHLv0G2R20lALTgzvPS/Article-View?node-id=0-1
Prototype - https://www.figma.com/proto/TNmgHLv0G2R20lALTgzvPS/Article-View?t=3kCcaO3bKBCKhXCl-1&node-id=7-92&scaling=contain&content-scaling=fixed

YOU HAVE TO DEVELOP THE SCREEN

### Use Case

Article Child View Click.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by rushiii3** [comment]
Hey @SB2318, you can assign me this task!
