### ISSUE TITLE
💡[Feature]:  Get Profile API Creation & update user information with article.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Option 1:** 
Update UserSchema with an array of written articles. 

**Option 2:** 
Create the following APIs: 

(i) getArticlesByUserId: Returns an array of articles. (Written by that particular user)

(ii) saveArticle: Saves articles for a specific user. (POST request)  (save articles, written by other user also, store whole article object here, not only id)

(iii) getSavedArticlesFromUserId: Retrieves saved articles for a specific user. 
(iv) unsaveArticles: Removes saved articles for a specific user.

getProfile: Retrieves user profile information.

### Use Case

API Integration for profile page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  I can work on that

**Comment by SB2318** [comment]
> @SB2318 I can work on that

@Ayushmaanagarwal1211 are u available for this?

**Comment by nishant0708** [comment]
Hey @SB2318 can I work on this?

**Comment by Ayushmaanagarwal1211** [comment]
> > @SB2318 I can work on that
> 
> @Ayushmaanagarwal1211 are u available for this?

Yes

**Comment by SB2318** [comment]
> Hey @SB2318 can I work on this?

Okay, I will get back to you, If he is unable to complete this. 😇
