### ISSUE TITLE
💡[Feature]:  Add action to the call icon and email icon in profile page.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Will brief 

### Use Case

NA

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by rushiii3** [comment]
Hey @SB2318, you can assign me this task!

**Comment by SB2318** [comment]
> Hey @SB2318, you can assign me this task!

Okay, as of now keep their random phone number & email. (Like someone@gmail.com, +91 234567890)

**Comment by rushiii3** [comment]
Okay

**Comment by rushiii3** [comment]
@SB2318 
When the user clicks the call button, then it will open the phone app with the number or initiate a phone call without user permission?

**Comment by SB2318** [comment]
Open the caller activity with the phone number.

**Comment by rushiii3** [comment]
Hey @SB2318, check #174
