### ISSUE TITLE
💡[Feature]: Podcast page design in figma

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/f48edfb9-57ef-4a9f-b39e-acc42a7df2c8)

To enhance the user experience, we will make the following modifications:

* Instead of displaying the rating, we can show the like count to better indicate the popularity of the article.
* We can incorporate download and share icons to provide users with convenient options for interacting with the content.
* In place of "Relevant Podcasts," we can feature a section called "Recent Podcasts You Have Listened To" or something similar. This will help users easily access the podcasts they have recently engaged with.
* To maintain consistency and provide a seamless experience, we can apply an app-relevant theme throughout the interface, ensuring a cohesive look and feel.

### Use Case

Podcasts Screen

### Benefits

FEATURE

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@rushii do you want to take a look on it?

**Comment by rushiii3** [comment]
@SB2318, Sure you can assign me

**Comment by SB2318** [comment]
> @SB2318, Sure you can assign me

Okay, please let me know either in mail (If I am not available in discord) or via discord, If you faces any problem.

**Comment by rushiii3** [comment]
@SB2318, I have doubt about the UI
is it a podcast page or a player page?

**Comment by SB2318** [comment]
> @SB2318, I have doubt about the UI is it a podcast page or a player page?

I understand you are talking about FullScreen UI. But this will be better If our theme is dark. For this I am thinking of some Background or LockScreen Notification.

As of now keep it simple.

**Comment by rushiii3** [comment]
Okayy

**Comment by rushiii3** [comment]
@SB2318, check discord
