### ISSUE TITLE
📝[Docs]: Translate all the existing articles into it's Hindi version.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggested Change

Create sub-folder, like hindi and english, store the respective articles there.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  can I try it

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  I have only 2 doubts can you please help me to clear that : 
- The placement of hindi translation like should i place this translation to the bottom of the english version of that article or create a new md file 
- In Hindi translation am i have to use like English Charachters that can be read as Hindi  or full  with Hindi charachters .

**Comment by SB2318** [comment]
> @SB2318 I have only 2 doubts can you please help me to clear that :
> 
> * The placement of hindi translation like should i place this translation to the bottom of the english version of that article or create a new md file
> * In Hindi translation am i have to use like English Charachters that can be read as Hindi  or full  with Hindi charachters .

hindi version of those article.

**Comment by SB2318** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Issue Description
> ## Task Area:
> Develop Branch : Data Source
> 
> ### Suggested Change
> Create sub-folder, like hindi and english, store the respective articles there.
> 
> ### Rationale
> _No response_
> 
> ### Urgency
> Medium
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [ ]  I'm a GSSOC'24 contributor
> * [ ]  I want to work on this issue

There are 6 articles, You have to prepare the hindi version of those, in a separate folder. like `./DataSource/Hindi.`

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  OK
