### ISSUE TITLE
📝[Docs]:  Chronic Pain (Long Term)

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Write with your creativity,

Include the following sections:

(i) OverView
(ii) Symptoms
(iii) Treatments
(iv) HomeCare
(v) Worst Case :
There may be situations where your brain creates the perception of pain, even though there is no actual physical harm. This can occur due to the signals that your brain sends, which may result in the experience of pain.

### Suggested Change

Given

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@nishant0708

**Comment by nishant0708** [comment]
Yess
