### ISSUE TITLE
💡[Feature]:  Hypertension - The Silent Killer  (English, Hindi, Tamil & Malay, Spanish)

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hypertension - The Silent Killer 

Provide Both  Hindi and English version of the article.

Suggestion:
(i) First Write the English article,
(ii) Then translate it to hindi.

### Use Case

Article Collection

### Benefits

For Application

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by suhanipaliwal** [comment]
Please assign this issue to me.

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318 Can i work on that

**Comment by SB2318** [comment]
@suhanipaliwal please give an update.

**Comment by SB2318** [comment]
@Damini2004

**Comment by Damini2004** [comment]
@SB2318 Assign this to me and review my PR.

**Comment by SB2318** [comment]
@Damini2004 any update?

**Comment by Damini2004** [comment]
> @Damini2004 any update? 

I have already created pr.

**Comment by SB2318** [comment]
please mentioned in the issue

**Comment by Damini2004** [comment]
@SB2318 https://github.com/SB2318/UltimateHealth/pull/221 
#221 Review it.

**Comment by suhanipaliwal** [comment]
> @suhanipaliwal please give an update.

I'll raise the pr today itself.

**Comment by SB2318** [comment]
Now, what should I do? 😂

**Comment by suhanipaliwal** [comment]
Well, this issue was assigned to me and I don't think it's the right way to contribute to open source in this way.
