### ISSUE TITLE
📝[Docs]: Stroke : Signs, Preventation and Recovery

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Stroke : Signs, Preventation and Recovery

Provide Both Hindi and English version of the article.

Suggestion:
(i) First Write the English article,
(ii) Then translate it to hindi.

### Suggested Change

Stroke : Signs, Preventation and Recovery

Provide Both Hindi and English version of the article.

Suggestion:
(i) First Write the English article,
(ii) Then translate it to hindi.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by ananyag309** [comment]
I am willing to work on this issue
