### ISSUE TITLE
📝[Docs]:  Alzheimer's Diseases: Understanding the Symptoms and Care

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Alzheimer's Diseases: Understanding the Symptoms and Care

Provide Both Hindi and English version of the article.

Suggestion:
(i) First Write the English article,
(ii) Then translate it to hindi.

### Suggested Change

Provide Both Hindi and English version of the article.

Suggestion:
(i) First Write the English article,
(ii) Then translate it to hindi.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nishant0708** [comment]
hey @SB2318 can i work on this?
