### ISSUE TITLE
💡[Feature]: Podcast Screen Implementation Frontend

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Podcast Screen

### Use Case

Application Screen

### Benefits

Feature

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ddb3aea0-544d-4c11-9887-77e5ac2673e9)

Figma Link: https://www.figma.com/design/vgTGx19tphLRtARn7Kxvun/Podcast-Page?node-id=0-1&t=0J2PPLZlBj3KI6zW-0
### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nipunh** [comment]
@SB2318 Can you please assign me this issue?

**Comment by divyesh-mali** [comment]
Please assign me this issue. I can work on it.

**Comment by SB2318** [comment]
@divyesh-mali  any update?

**Comment by SB2318** [comment]
@rushiii3 are u want to work on this?

**Comment by rushiii3** [comment]
Sure!

**Comment by divyesh-mali** [comment]
> @divyesh-mali any update?

Sorry I was out of station and my latop was not there with me since a week. No worries I will pick up another issue and work on it.

**Comment by rushiii3** [comment]
@SB2318 , check if you need any changes! #284
