### ISSUE TITLE
💡[Feature]:   Follow and Unfollow functionality from backend.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Here You have to implement follow and unfollow a user functionality from backend. (With the updated user schema)

You have to create following APIs.
(i) followAuthor
(ii) unfollowAuthor
updateFollowCount as well.

You can take reference of articleLikeAndDislike API, to understand the requirement.  😇

### Use Case

Application Backend

### Benefits

Feature

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nishant0708** [comment]
hey Can i work on this

**Comment by nishant0708** [comment]
Hey @SB2318  should I add on more field in user as followers :0 as default and then write API for that correct?
