### ISSUE TITLE
💡[Feature]: Make Categories Dynamic In the Home Page .(Integrate Tag API)

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

* You have to integrate Tag API.

![image](https://github.com/user-attachments/assets/fa7e5b52-4055-4ed4-a95d-975de2f115a2)

Then have to populate the tags here.

### Use Case

Application Feature.

If you found there are currently no tags available, (Then please post the tag explicitly using postman or other similar available tools)

For any queries Contact me on discord, or reach out via <a href="mailto:ultimate.health25@gmail.com"> email</a>.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by rushiii3** [comment]
Hey @SB2318, you can assign me this task

**Comment by rushiii3** [comment]
@SB2318, check if changes are needed for #217
