### ISSUE TITLE
📝[Docs]: COPD (Chronic obstructive pulmonary disease)

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Cover the following points:

* About **COPD**
* Fact 
* Myth (COPD symptoms can get worse quickly)
* Living well with COPD (HomeCare & Exercise)
* Causes of COPD
* Syndroms
* Social Awareness

For your reference: (You can include the info.)

 ### Myth about COPD (Social Awareness)

    <ul style='list-style-type: none;'><li><p> <strong> Only smokers get COPD</strong> </p><p>Common myths about COPD that can stop people from getting the right treatment.</p><p>Although smoking is the main cause of COPD, not everyone who has COPD is a smoker. COPD is also caused by:</p><ul><li>Fumes and dust</li><li>Air pollution</li><li>Genetic tendancy to the disease (for example alpha-1-antitrypsin deficiency)</li><li>passive smoking</li></ul></li><li><p> <strong>You can’t exercise if you have COPD</strong> </p><p>Exercising is actually recommended to individuals with COPD. Regular exercise can improve your breathing, make your symptoms less severe and improve your quality of life.</p></li><li><p> <strong>COPD only affects the lungs</strong> </p><p>COPD primarily affects the lungs but it also can cause:</p><ul><li>weight loss</li><li>tiredness and fatigue</li><li>swollen ankles</li><li>high blood pressure</li></ul><p>COPD can also increases the risk of heart disease and like any long term condition, depression and mental illness can also come into play.</p></li><li><p> <strong>COPD is untreatable</strong> </p><p>COPD has no cure yet, but this doesn’t mean that it’s untreatable. By improving your lifestyle, you can live a long and full life with COPD. A common misinterpretation is that ‘Chronic’ means really bad or extreme rather than long term.</p><p>Individuals who exercise more and maintain a healthy weight can experience less severe symptoms and enjoy a better quality of life. Practising breathing techniques could also increase your lung capacity.</p><p>If you smoke, quitting smoking will also help to combat COPD symptoms.</p></li><li><p> <strong>COPD is a man’s disease</strong> </p><p>This is simply not true. Both men and women can have COPD.</p><p>In fact in Scotland, women develop the condition with a lower exposure to smoking than men.</p></li><li><p> <strong>Only older people get COPD</strong> </p><p>Many individuals with COPD are over 65, however you can experience COPD symptoms at any age.</p><p>It’s thought COPD is only diagnosed when individuals’ symptoms can no longer be ignored. They may have been experiencing these symptoms much earlier in their 40’s and 50’s and done nothing about it.</p><p>It’s also thought that two thirds of people with COPD are undiagnosed and go undiagnosed until later life.</p></li><li><p> <strong> Smoking causes COPD </strong> </p><p>It’s never to late to quit smoking, as this could slow the progression of COPD. COPD will not go away if you quit smoking, but it could benefit your health. Quitting could potentially allow some lung function to return.</p></li></ul>
         

### Suggested Change

**Contribute Both Hindi and English article**

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by ananyag309** [comment]
Please assign this issue to me
