### ISSUE TITLE
📝[Docs]: Dehydration: The Silent Threat to Your Health

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Cover the following topics:
* About
* Dehydration Symptoms
* Causes
* Home Care & Treatment
* When to connect a medical professional?

### Suggested Change

Both the Hindi And English Version.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Aditijainnn** [comment]
please assign this to me under Gssoc

**Comment by Aditijainnn** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Issue Description
> 
> Cover the following topics:
> 
>     * About
> 
>     * Dehydration Symptoms
> 
>     * Causes
> 
>     * Home Care & Treatment
> 
>     * When to connect a medical professional?
> 
> 
> ### Suggested Change
> 
> Both the Hindi And English Version.
> ### Rationale
> 
> _No response_
> ### Urgency
> 
> Medium
> ### Record
> 
>     * [x]  I have read the Contributing Guidelines
> 
>     * [ ]  I'm a GSSOC'24 contributor
> 
>     * [ ]  I want to work on this issue

please assign this to me

**Comment by Damini2004** [comment]
@Aditijainnn Are you working on it.

**Comment by Aditijainnn** [comment]
yes
