### ISSUE TITLE
💡[Feature]:  Add Back Button in EditorScreen & PreviewScreen

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/64908660-22bb-4475-aa2a-0e5f13aa85e4)

Decrease the font size  and instead of Preview You can use ImageButton using proper icon.

### Use Case

Feature

### Benefits

Application Enhancement

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Vaibhav-kesarwani** [comment]
@SB2318  Please assign this issue to me. I like to work on this

**Comment by SB2318** [comment]
@Vaibhav-kesarwani any update?

**Comment by SB2318** [comment]
@rushiii3 would you like to work on this?

**Comment by rushiii3** [comment]
Suree!

**Comment by SB2318** [comment]
@rushiii3  see the updates in requirements, and complete your task accordingly as soon as possible.

**Comment by rushiii3** [comment]
> @rushiii3 see the updates in requirements, and complete your task accordingly as soon as possible.

Yaa working!
