### ISSUE TITLE
brief about the project ?

### ISSUE THREAD

**Issue by Samarjiit** [SB2318/UltimateHealth#2]

**Comment by SB2318** [comment]
Hello @Samarjiit 
Great to hear that, You are interested in the react-native framework and you want to explore it more.
Yes, Then this project is for you.
Don't worry, **GSSOC'24** is long-term, It is almost there for you for the next 3 months.
And I believe that we can achieve many more milestones together.

Project readme will updated by today's EOD, soon you will get your answer.

Keep patience, Keep learning, and Keep contributing!
