### ISSUE TITLE
Immediate Issue: APIError: throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))

### ISSUE THREAD

**Issue by Nirvanjha2004** [SB2318/UltimateHealth#20]
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/70cdaeee-9ad1-41fa-b890-36e4c2dc124e)

**Comment by Krishnabhattacharya** [comment]
I can di it , please assign me this

**Comment by rushiii3** [comment]
Hey @SB2318 , assign me this issue

**Comment by meghanagottapu** [comment]
hi @SB2318 , can I take up this issue?

**Comment by SB2318** [comment]
@Nirvanjha2004  Let me know will you want to work on this issue?

**Comment by Nirvanjha2004** [comment]
@SB2318  Yes... I will work on it...

**Comment by SB2318** [comment]
@Nirvanjha2004 please share your update.

**Comment by Krishnabhattacharya** [comment]
Please assign to me...i will solve it
