### ISSUE TITLE
💡[Feature]: Implement User Article Engagement (Read & Write Count of articles) (Backend)

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As part of our user analytics and engagement tracking, we need to implement a system to collect record when a user has completely read an article and measure the time spent reading it. This will help us understand user behavior and provide insights on how to improve our content and user experience.

### Task 1: Update UserSchema

Add the following properties to the UserSchema:

readArticles: An array of objects, where each object contains:
  * articleId: The ID of the read article
  * readingDate: The date and time when the article was read

### Task 2: Create APIs

Create the following APIs:

**(i) updateReadArticles**

**Endpoint:**           /api/update-read-articles
**Method:**             POST
**Request Body:**   articleId (ID of the article bein read)
**Response:**         Update the user's readArticles array with the new article ID and current timestamp

**(ii) collectMonthlyRecordsForReading**

  **Endpoint:**  /api/collect-monthly-records-for-reading
   **Method:**   GET
**Request Params:** month (optional, default to current month)
**Response:** Return the number of articles reads by the user daily with reading date and time.

For example :
```
{
   status: true,
   data:{
      [
       {
           articleReadCount: 0,
            date: '01-07-24',
       },
       
        {
           articleReadCount: 1,
            date: '02-07-24',
       },
   //.... So On
     ]
   }
}
```

**(iii) collectMonthlyRecordsForWriting**

**Endpoint:** /api/collect-monthly-records-for-writing
**Method:** GET
**Request Params:** month (optional, default to current month)
**Response:** Return a list of articles written by the user in the specified month, including the publication date and time

```
{
   status: true,
   data:{
      [
       {
           articlePostCount: 1, // It will be taken by considering publication date
            date: '01-07-24',
       },
       
        {
           articlePostCount: 0,
            date: '02-07-24',
       },
   //.... So On
     ]
   }
}
```

### Use Case

Feature

### Benefits

Application

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by nishant0708** [comment]
hey @SB2318 Can i work in this issue

**Comment by SB2318** [comment]
@nishant0708  please read the description & let me know your availability for the task.

**Comment by nishant0708** [comment]
Yes I can do this

**Comment by nishant0708** [comment]
hey @SB2318 Have Anyone Changed Article controllers ? beacuse its not working . There are errors in Article controllersa

![image](https://github.com/user-attachments/assets/a3b7ee4f-309b-4a2c-b700-6d6d9a785443)

**Comment by nishant0708** [comment]
there are Error in Create Article api as well .

> hey @SB2318 Have Anyone Changed Article controllers ? beacuse its not working . There are errors in Article controllersa
> 
> ![image](https://private-user-images.githubusercontent.com/101548649/352004623-a3b7ee4f-309b-4a2c-b700-6d6d9a785443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTI1ODMsIm5iZiI6MTcyMTg5MjI4MywicGF0aCI6Ii8xMDE1NDg2NDkvMzUyMDA0NjIzLWEzYjdlZTRmLTMwOWItNGEyYy1iNzAwLTZkNmQ5YTc4NTQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNzI0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDEwOWE1MzgxMDg0YzI0ZDU0OTk5YTM2Njg2NmZkYWY1MzlkYjI5ZmJiZjgxMTJiNjg5MzVlOTgyODc2Y2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f_NRfeat7MyhghnDxkhTjWhuTvsDSebL5k13xdhfELw)

**Comment by SB2318** [comment]
Share the image on discord

**Comment by nishant0708** [comment]
hey @SB2318 send..

**Comment by Ayushmaanagarwal1211** [comment]
@nishant0708  Yes bro i changed create article api last week but i didn't change any functionality like here 
![image](https://github.com/user-attachments/assets/230432d0-ed86-496f-8d72-6a6566ae67af)
I am just adding 
![image](https://github.com/user-attachments/assets/58344d1a-06df-4495-b7ac-49970c1816a8)
In this i just add a function to check whether the user exist or not so i think it doesn't change functionality
If their is any error please let me know

**Comment by SB2318** [comment]
> @nishant0708 Yes bro i changed create article api last week but i didn't change any functionality like here ![image](https://private-user-images.githubusercontent.com/118350936/352075264-230432d0-ed86-496f-8d72-6a6566ae67af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQ1MDYsIm5iZiI6MTcyMTkwNDIwNiwicGF0aCI6Ii8xMTgzNTA5MzYvMzUyMDc1MjY0LTIzMDQzMmQwLWVkODYtNDk2Zi04ZDcyLTZhNjU2NmFlNjdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMDQzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODRhZGUxNDIxZDhlYzYyZjFhZjg2ZWJhMTE2YWM5MTk2YWM2YjdhNmQxYzMzOWIzMTkxZGQ5NGJhOTAwNGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wryXYoodz9_lZsPIgNFfs2xXKp-hEP0uG2ILTfXIxUQ) I am just added ![image](https://private-user-images.githubusercontent.com/118350936/352075517-58344d1a-06df-4495-b7ac-49970c1816a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQ1MDYsIm5iZiI6MTcyMTkwNDIwNiwicGF0aCI6Ii8xMTgzNTA5MzYvMzUyMDc1NTE3LTU4MzQ0ZDFhLTA2ZGYtNDQ5NS1iN2FjLTQ5OTcwYzE4MTZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMDQzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODhlMDFlYjZhYzc5YzBkYmRlNDJjN2IxODM0MWVhZDAyMzA5ZGU0ZjhiNDk2YTliODU3MDhkMDg3Mjk0NWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nz2ULHxTcfqBFuHOfpH621GL0UeJvp8JKXlCBZKVDVQ) In this i just add a function to check whether the user exist or not so i think it doesn't change functionality If their is any error please let me know

No, no, this is not the problem, He needs to debug the code a little bit. That's why he asking

**Comment by Ayushmaanagarwal1211** [comment]
> > @nishant0708 Yes bro i changed create article api last week but i didn't change any functionality like here ![image](https://private-user-images.githubusercontent.com/118350936/352075264-230432d0-ed86-496f-8d72-6a6566ae67af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQ1MDYsIm5iZiI6MTcyMTkwNDIwNiwicGF0aCI6Ii8xMTgzNTA5MzYvMzUyMDc1MjY0LTIzMDQzMmQwLWVkODYtNDk2Zi04ZDcyLTZhNjU2NmFlNjdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMDQzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODRhZGUxNDIxZDhlYzYyZjFhZjg2ZWJhMTE2YWM5MTk2YWM2YjdhNmQxYzMzOWIzMTkxZGQ5NGJhOTAwNGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wryXYoodz9_lZsPIgNFfs2xXKp-hEP0uG2ILTfXIxUQ) I am just added ![image](https://private-user-images.githubusercontent.com/118350936/352075517-58344d1a-06df-4495-b7ac-49970c1816a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDQ1MDYsIm5iZiI6MTcyMTkwNDIwNiwicGF0aCI6Ii8xMTgzNTA5MzYvMzUyMDc1NTE3LTU4MzQ0ZDFhLTA2ZGYtNDQ5NS1iN2FjLTQ5OTcwYzE4MTZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMDQzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODhlMDFlYjZhYzc5YzBkYmRlNDJjN2IxODM0MWVhZDAyMzA5ZGU0ZjhiNDk2YTliODU3MDhkMDg3Mjk0NWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nz2ULHxTcfqBFuHOfpH621GL0UeJvp8JKXlCBZKVDVQ) In this i just add a function to check whether the user exist or not so i think it doesn't change functionality If their is any error please let me know
> 
> No, no, this is not the problem, He needs to debug the code a little bit. That's why he asking

Ya ya no problem and if their is any  problem  from my side please let me know maybe i did some mistake i fix fixed that

**Comment by nishant0708** [comment]
> @nishant0708 Yes bro i changed create article api last week but i didn't change any functionality like here ![image](https://private-user-images.githubusercontent.com/118350936/352075264-230432d0-ed86-496f-8d72-6a6566ae67af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDgxMDgsIm5iZiI6MTcyMTkwNzgwOCwicGF0aCI6Ii8xMTgzNTA5MzYvMzUyMDc1MjY0LTIzMDQzMmQwLWVkODYtNDk2Zi04ZDcyLTZhNjU2NmFlNjdhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMTQzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmQ2MzIzODlhMzdmYThjODAwOWQ3NDE1NWZhYjMyNjg4MDU0ZTRhZjhlMDU1ZWEwNGM0NTMyMWE2NjYyN2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-tb1u73o7AScpAFSjSQl34kU_iAiEPMTXTcxrzWh7nA) I am just added ![image](https://private-user-images.githubusercontent.com/118350936/352075517-58344d1a-06df-4495-b7ac-49970c1816a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDgxMDgsIm5iZiI6MTcyMTkwNzgwOCwicGF0aCI6Ii8xMTgzNTA5MzYvMzUyMDc1NTE3LTU4MzQ0ZDFhLTA2ZGYtNDQ5NS1iN2FjLTQ5OTcwYzE4MTZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxMTQzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGMwZDEwNzhlMjQ5MTYzYWE3NmU0Y2UzMzcyMWJhZjMwMDFhMzM5N2EzMDg0ZGYxNzgzMDc3YWQwMzdmMjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mIscAJP98ePJI3XBfV51WCUfQpK1-k6XrYmmbuuLwiw) In this i just add a function to check whether the user exist or not so i think it doesn't change functionality If their is any error please let me know

Hey can you tell pr no.?

**Comment by Ayushmaanagarwal1211** [comment]
#175

**Comment by nishant0708** [comment]
Hey @Ayushmaanagarwal1211 did you checked the  api by creating article

**Comment by Ayushmaanagarwal1211** [comment]
Yes bro this was working

**Comment by Ayushmaanagarwal1211** [comment]
but i again clone the code and check then i saw the code changes a little bit 

![image](https://github.com/user-attachments/assets/a4be0e78-d477-4701-8707-4ad8f83e37fc)

**Comment by Ayushmaanagarwal1211** [comment]
@nishant0708 wait i think i found a bug it's due to user model not imported wait i will correct it

**Comment by nishant0708** [comment]
@Ayushmaanagarwal1211 I will fix that let it be. And that's not a bug

**Comment by Ayushmaanagarwal1211** [comment]
hmm well i opened a pr i will close then

**Comment by SB2318** [comment]
@nishant0708 & @Ayushmaanagarwal1211  📈 It’s incredible to see how we can now pinpoint the source of any issue. 🚀 This is a massive win for the project, especially as we near the finish line of the open source program! 🏁.

You both are doing very well. 😇
