### ISSUE TITLE
📝[Docs]: Calcium Deficiency Diseases

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Please cover the following topics.

 * What happens when calcium levels are low?
 * Symptoms
 * Muscle Problems
 * Extreme Fatigue
 * Dental Problems

### Suggested Change

Calcium Deficiency Diseases:
Both English and Hindi Version.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318 Can i work on this

**Comment by SB2318** [comment]
> @SB2318 Can i work on this

Yes sure!
