### ISSUE TITLE
📝[Docs]:  IRON DEFICIENCY DISEASES

### ISSUE THREAD

**Issue by Damini2004** [SB2318/UltimateHealth#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Iron deficiency can lead to several health issues, collectively referred to as iron-deficiency diseases. The most common iron deficiency disease is iron-deficiency anemia, but iron deficiency can also contribute to other health problems.

### Suggested Change

Iron-deficiency anemia is a condition resulting from insufficient iron levels, leading to decreased production of hemoglobin, the oxygen-carrying protein in red blood cells. This deficiency impairs oxygen transport in the body, causing symptoms such as fatigue, weakness, pale skin, shortness of breath, dizziness, cold extremities, and brittle nails. Additional complications from iron deficiency include restless legs syndrome, cognitive impairment, compromised immune function, and increased risks during pregnancy.

Current Symptoms Section:

Fatigue and weakness
Pale skin and mucous membranes
Shortness of breath
Dizziness or lightheadedness
Cold hands and feet
Brittle nails
Cravings for non-nutritive substances (pica), such as ice or dirt
Headaches
Poor appetite, especially in infants and children
Restless legs syndrome

### Rationale

Comprehensive Coverage: The revised description provides a more detailed explanation of iron-deficiency anemia and its broader impact on health.
Enhanced Symptom List: Including cognitive impairment, immune function issues, and pregnancy complications gives a fuller picture of iron deficiency's effects.
Clarity: The revised wording is clearer and more informative, helping readers understand the seriousness and scope of iron deficiency diseases.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318  Hii i want to that is this Issue is Up for grabs

**Comment by Damini2004** [comment]
@Ayushmaanagarwal1211 Can you work on another issue, as this issue created by me so i wanted to contribute.

**Comment by Ayushmaanagarwal1211** [comment]
Yes sure

**Comment by SB2318** [comment]
@Damini2004  You have to provide both English & Hindi article.

**Comment by Damini2004** [comment]
@SB2318 Ya sure mam, Kindly assign this to me.
