### ISSUE TITLE
💡[Feature]: Profile API integration

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Make Profile Screen Dynamic.

### Use Case

Feature

### Benefits

Application

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by rushiii3** [comment]
@SB2318, you can assign me this task.

**Comment by rushiii3** [comment]
@SB2318, Check if you need changes. #235
