### ISSUE TITLE
Backend Task: Set Up MongoDb database for the backend project

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#21]
Task Description:

(i)  clone the repository: `https://github.com/SB2318/UltimateHealth.git`
(ii) check out the branch: `git checkout ultimate_health_backend`

(iii) **Install [node js:](https://nodejs.org/en/download)**

(iv) Open the folder on vs code

(v) Open a new terminal

(vi) Install express.js 

`npm install express`

(vi) start the server:
      node server.js
      
  Your task is only to set up the **Mongodb** database with the project.

Create some demo data to implement only POST CRUD operation, And it will return the message ' data saved successfully

**Comment by BHS-Harish** [comment]
Hello @SB2318 

I would like to setup the backend server with mongodb.

Please assign the issue to me

Thanks in advance

**Comment by meghanagottapu** [comment]
Hi @SB2318 
I would like to set up the whole server for complete backend functionality. please assign this issue to me.
Thanks

**Comment by SB2318** [comment]
@meghanagottapu I appreciate your ability! ❤️, But as an open source program we have to give a chance to all participants,

But, we can receive one of your effective contributions. Please stay tuned to the project and keep contributing!

**Comment by kart2004** [comment]
Hello, I am Karthik Prakash. I would like to set up MongoDb for the backend project. Could you please assign this to me 
@SB2318. 
Thanks

**Comment by Krishnabhattacharya** [comment]
Hello,
I will do it in a efficient way, please assign me the task.

**Comment by soham0005** [comment]
Hello @meghanagottapu, have you started working on this issue? please let me know as after your task setup I have been assigned one issue in this project

**Comment by SB2318** [comment]
closed by #31
