### ISSUE TITLE
💡[Feature]:  Integrate Article API : Fetch article data from api.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Fetch article data from api & display it to the screen.

### Use Case

Feature

### Benefits

App

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Ayushmaanagarwal1211** [comment]
@SB2318 can i work on it

**Comment by rushiii3** [comment]
@SB2318, you can assign me this task if you provide the dataset

**Comment by SB2318** [comment]
> @SB2318, you can assign me this task if you provide the dataset

Okay, I need to update the dataset a little bit. will let u know soon.
