### ISSUE TITLE
📝[Docs]: Translate First Six  available articles into Spanish Language. 

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

**Task Area:** Develop Branch
**./DataSource**

### Suggested Change

Documentation
You have to create a folder for the particular folder and contribute there. 

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Damini2004** [comment]
@SB2318 Kindly assign this to me. After i resolved previous issue created by me.

**Comment by Damini2004** [comment]
@SB2318 can I work on it ?

**Comment by SB2318** [comment]
@Damini2004 Please start your work after 2 hours from now. 
Otherwise, your PR will be discarded.

**Comment by SB2318** [comment]
> @Damini2004 Please start your work after 2 hours from now. Otherwise, your PR will be discarded.

I will update the DataSource folder, then only you can start work. 
Your work area will be develop branch.

With your PR, I want to see my changes.

**Comment by Damini2004** [comment]
@SB2318 sure!! 
Did you updated the folder.
Once you done it then mention me i will start work on it.

**Comment by SB2318** [comment]
@Damini2004  All articles from **./DataSource/English** folder of **develop** branch.

**Comment by Damini2004** [comment]
@SB2318   Didn't get it.
I have translated all the article into spanish just waiting for your response to create PR..

**Comment by Damini2004** [comment]
@SB2318 Should i raise the PR ?

**Comment by SB2318** [comment]
> @SB2318 Should i raise the PR ?

Make sure you fulfil those requirements:

(i) You have checkout **develop** branch.
(ii) Your branch(**develop**) updated with the following commit
     https://github.com/SB2318/UltimateHealth/commit/7353e4e4c58ac3b9c2b2f5aca5e04aaf0400ef2f
     
(iii) You provide translations for all the 13 articles available in the **Engilish** folder.
      Folder Link: https://github.com/SB2318/UltimateHealth/tree/develop/DataSources/English
      
(iv) You have created PR against **develop** branch.

**Comment by Damini2004** [comment]
@SB2318 i have to create folder for spanish language right ? as you not created it

**Comment by SB2318** [comment]
Yes

**Comment by Damini2004** [comment]
@SB2318 Can i do this in two PR ?

**Comment by SB2318** [comment]
Yes, but make sure that no merge conflict are there between those 2 PRs.

**Comment by Damini2004** [comment]
okk mam
