### ISSUE TITLE
📝[Docs]:  Vitamin D and Iron Deficiency disease adding in Marathi Language

### ISSUE THREAD

**Issue by Damini2004** [SB2318/UltimateHealth#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

📝[Docs]:  Vitamin D and Iron Deficiency disease adding in Marathi Language

### Suggested Change

📝[Docs]:  Vitamin D and Iron Deficiency disease adding in Marathi Language

### Rationale

📝[Docs]:  Vitamin D and Iron Deficiency disease adding in Marathi Language

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@Damini2004  complete your task within 30th July
