### ISSUE TITLE
📝[Docs]: Translate Rest Seven articles into Spanish Language.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

#212 

### Suggested Change

 #212 

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@Damini2004  would you like to work on this?

**Comment by Damini2004** [comment]
@SB2318 Yes assign it to me.
