### ISSUE TITLE
📝[Docs]:  Iodine Deficiency Disease with translation into English,Hindi,Malay,Spanish,Tamil

### ISSUE THREAD

**Issue by Damini2004** [SB2318/UltimateHealth#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

 Iodine Deficiency Disease with translation into English,Hindi,Malay,Spanish,Tamil

### Suggested Change

 Iodine Deficiency Disease with translation into English,Hindi,Malay,Spanish,Tamil

### Rationale

 Iodine Deficiency Disease with translation into English,Hindi,Malay,Spanish,Tamil

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@Damini2004 no more new articles.

**Comment by Damini2004** [comment]
> @Damini2004 no more new articles.

Why ? @SB2318

**Comment by SB2318** [comment]
> > @Damini2004 no more new articles.
> 
> Why ? @SB2318

Existing articles left

**Comment by Damini2004** [comment]
> > > @Damini2004 no more new articles.
> > 
> > Why ? @SB2318
> 
> Existing articles left

Can I work on it ?

**Comment by Damini2004** [comment]
> > > > @Damini2004 no more new articles.
> > > 
> > > Why ? @SB2318
> > 
> > Existing articles left
> 
> Can I work on it ?

You can even assign me to convert it into another language too

**Comment by SB2318** [comment]
@Damini2004  complete your task within 30th July
