### ISSUE TITLE
📝[Docs]: Exercise and Its Role in Preventing Diseases

### ISSUE THREAD

**Issue by sreevidya-16** [SB2318/UltimateHealth#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I want to add article based on the topic "Exercise and Its Role in Preventing Diseases"
Kindly assign this issue to me under GSSOC'24

### Suggested Change

NA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@sreevidya-16 complete your task within 30th July
