### ISSUE TITLE
💡[Feature]: EditProfile frontend implementation

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

EditProfile frontend implementation

### Use Case

EditProfile frontend implementation

Figma Link : [EditProfile UI](https://www.figma.com/design/1xtdVazJsLTzquPOcAKvbO/Edit-Profile?node-id=0-1&t=O1iFC6iaJEzaGGoJ-1)

### Benefits

Feature

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@rushiii3 Please create PR for your assigned task, and let me know your availability for this task.

**Comment by rushiii3** [comment]
@SB2318, you may assign me this task!
Profile API integration is also completed.

**Comment by SB2318** [comment]
> @SB2318, you may assign me this task! Profile API integration is also completed.

Create PR and Mind it to complete this task within 30th July.

**Comment by rushiii3** [comment]
Okay
