### ISSUE TITLE
Restructure the Project: Backend and Frontend Separate Directory

### ISSUE THREAD

**Issue by jaickeyminj** [SB2318/UltimateHealth#24]
Hi,

Considering the project, which consists of both frontend and backend code. I am suggesting to make two separate directories.
Here's what would happen if we put both React and Express code in the same folder:

- Organizational Confusion: Mixing front-end and back-end code in the same folder can lead to confusion and make it harder to maintain and understand your project's structure.

- Build Process Complexity: React applications typically have a build process that transpiles JSX, bundles JavaScript files, and optimizes assets. Express applications, on the other hand, don't typically require such build steps. Combining these different build processes can be challenging.

- Development Server: React applications often come with a development server (like Create React App's development server) that serves the React application locally during development. Express applications also typically have a development server. Running both servers simultaneously in the same folder could cause conflicts.

- Deployment Complexity: Deploying a combined React and Express application may require more complex deployment configurations. You may need to configure your deployment process to build and serve the React front end separately from the Express back end.

- Dependencies: React and Express have different sets of dependencies. Mixing them together may lead to version conflicts or unnecessary dependencies.

**I am attaching a screenshot of my project where I have followed this hierarchy.** 

![image](https://github.com/SB2318/UltimateHealth/assets/95216865/c11799ac-f88f-42e1-9d5c-221ad0bd443f)

**Comment by jaickeyminj** [comment]
Hi @SB2318 ,

Please look into this issue and assign it to me.
Thanks!

**Comment by SB2318** [comment]
> Hi @SB2318 ,
> 
> Please look into this issue and assign it to me. Thanks

I was thinking of replacing it with a submodule, but your idea is more beginner-friendly. Go for it.👍

**Comment by solankybasant** [comment]
Hello @SB2318 
I am interested in taking on the development work for our upcoming project. I have experience with the required tech stack, including Node.js, Express.js, MongoDB, PostgreSQL, and React. Given my familiarity with these technologies, I am confident I can efficiently handle front-end and back-end tasks.

**Comment by SB2318** [comment]
> Hello @SB2318 I am interested in taking on the development work for our upcoming project. I have experience with the required tech stack, including Node.js, Express.js, MongoDB, PostgreSQL, and React. Given my familiarity with these technologies, I am confident I can efficiently handle front-end and back-end tasks.

Thanks for your participation.🫶
Please stay tuned for the project.
The first assignee has 3 days left on his hand.

**Comment by SB2318** [comment]
@jaickeyminj It does not mean you have to do the work conventionally. Find your way and complete the task, as soon as possible.

Hope I am clear to you with the requirements.

**Comment by jaickeyminj** [comment]
Hi @SB2318 ,

The has already been done and is ready to be reviewed by you. I have also tagged you in the PR, may be you missed it.
PR link - [https://github.com/SB2318/UltimateHealth/pull/27](url)

Requesting you to review it at the earliest.
Thanks!

**Comment by SB2318** [comment]
closes by #37
