### ISSUE TITLE
📝[Docs]: Role of Diet in Managing Autoimmune Diseases converting into remaining language

### ISSUE THREAD

**Issue by Damini2004** [SB2318/UltimateHealth#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Role of Diet in Managing Autoimmune Diseases converting into remaining language

### Suggested Change

Role of Diet in Managing Autoimmune Diseases converting into remaining language

### Rationale

Role of Diet in Managing Autoimmune Diseases converting into remaining language

I will do it in 2 PR 
Kindly assign this to me.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
