### ISSUE TITLE
📝[Docs]: Science of Happiness: How it Affects Your Health in English & Hindi

### ISSUE THREAD

**Issue by revanth1718** [SB2318/UltimateHealth#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I want to add information on this topic - "Science of Happiness: How it Affects Your Health"
@SB2318, please assign me this issue
I will complete this by tonight, please assign me this @SB2318 

### Suggested Change

I want to add information on this topic - "Science of Happiness: How it Affects Your Health"

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by revanth1718** [comment]
@SB2318, assign me this issue

**Comment by SB2318** [comment]
> @SB2318, assign me this issue

Sorry, similar article available. 😇
