### ISSUE TITLE
Implement User Authorization and Authentication

### ISSUE THREAD

**Issue by Yashasvi213** [SB2318/UltimateHealth#26]
**Expected Behavior:**

- Users should be required to sign up and log in to access certain features of the application.
- Upon successful login, users should be authenticated and authorized based on their roles to perform specific actions.

**Proposed Solution:**

- Implement user authentication using JWT (JSON Web Tokens) to securely manage user sessions.
- Implement signup, login, logout, and password reset functionality with appropriate validation and error handling.
- Set up protected routes in the backend to restrict access to authorized users only.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by sagargiradkar** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by SB2318** [comment]
@sagargiradkar , @anshdeep0504 , @Yashasvi213  The issue is similar to #18.

**Comment by sagargiradkar** [comment]
@SB2318 Can you please assign new issue

**Comment by SB2318** [comment]
> @SB2318 Can you please assign new issue

Sure! New issues will come soon! Please stay tuned with the project and Keep contributing!
