### ISSUE TITLE
📝[Docs]: Convert all articles in Bengali

### ISSUE THREAD

**Issue by ananyag309** [SB2318/UltimateHealth#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Converting articles into Bengali can expand the audience reach, cater to Bengali-speaking individuals, enhance by targeting Bengali searches, and promote inclusivity by providing information in multiple languages.

### Suggested Change

The article is already in different language - i wish to convert in bengali so that india north east range is also covered as most of the languages is south indian

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@ananyag309  wait for my update, I will inform.

**Comment by ananyag309** [comment]
> @ananyag309 wait for my update, I will inform by today.

ma'am i thought you have assigned it to me so i completed it. i am sorry if any changes are needed i will do it. and for French one i haven't yet done
