### ISSUE TITLE
📝[Docs]: The Impact of Stress on Physical and Mental Health: Strategies for Managing Stress in Daily Life (Hindi & English)

### ISSUE THREAD

**Issue by ananyag309** [SB2318/UltimateHealth#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

add article on The Impact of Stress on Physical and Mental Health: Strategies for Managing Stress in Daily Life

### Suggested Change

Understanding Stress
Effects of Stress on Physical Health
Effects of Stress on Mental Health
Strategies for Managing Stress
Seeking Professional Help

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
You can start work on it.
