### ISSUE TITLE
📝[Docs]: Understanding Insomnia: Causes, Symptoms, and Solutions

### ISSUE THREAD

**Issue by AsmitaMishra24** [SB2318/UltimateHealth#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This article will provide comprehensive information on insomnia, including its causes, symptoms, and various solutions to manage and overcome it. This content will help enhance our health and wellness section, providing valuable information to our readers.

### Suggested Change

1. Introduction
2. Causes of Insomnia
3. Symptoms of Insomnia
4. Solutions for Insomnia

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AsmitaMishra24** [comment]
@SB2318, please assign me this issue

**Comment by Damini2004** [comment]
@AsmitaMishra24 Are you working on it ?

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 Are you working on it ?

@Damini2004, yes
