### ISSUE TITLE
📝[Docs]: Hypertension: The silent Killer (Tamil & Malay, Spanish)

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Translate the document into Tamil , Malay & Spanish

### Suggested Change

Translate the document into Tamil , Malay & Spanish

### Rationale

Translate the document into Tamil , Malay & Spanish

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@suhanipaliwal  would you like to take the issue?

**Comment by Hemu21** [comment]
@SB2318  can you please assign me

**Comment by Aditijainnn** [comment]
please assign

**Comment by suhanipaliwal** [comment]
> @suhanipaliwal would you like to take the issue You can provide your own. 😇

Yes sure
