### ISSUE TITLE
📝[Docs]: Effect of ECT treatment on mental and physical health

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Drawbacks and Limitations of ECT Treatment
Success Rates of ECT Treatment
Is ECT Treatment Truly Worth It?
Which Mental Health Conditions Necessitate ECT?
The Importance of Social Awareness Regarding ECT

### Suggested Change

English & Hindi

### Rationale

NA

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by AsmitaMishra24** [comment]
@SB2318, ma'am please assign me this issue.
