### ISSUE TITLE
Change the status bar color and application logo

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#29]
Task Description :
You need to change the status bar color and the logo of the application. 

Source: https://github.com/SB2318/UltimateHealth/blob/ultimate_health_frontend/src/Theme.js

Continuation #14

Please start work once #14 will complete.

Thanks for your patience, Keep Contributing!

**Comment by rushiii3** [comment]
Hey @SB2318 , assign me this task

**Comment by viththagi** [comment]
Hi @SB2318 i would like to work on this issue

**Comment by rushiii3** [comment]
Hey @SB2318, 
I have changed the app icon and status bar. Kindly review 
PR link : [https://github.com/SB2318/UltimateHealth/pull/36](url)

**Comment by SB2318** [comment]
close by #36
