### ISSUE TITLE
📝[Docs]: Side Effect of Chemotherapy

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

 Side Effect of Chemotherapy

### Suggested Change

 English & Hindi

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@Damini2004

**Comment by Damini2004** [comment]
@SB2318  Yes mam assign this to me.

**Comment by Damini2004** [comment]
@SB2318 Do i have to convert it into 6 languages too ?

**Comment by SB2318** [comment]
> @SB2318 Do i have to convert it into 6 languages too ?

Not needed, But try to make the article better, with some valuable info.

**Comment by Damini2004** [comment]
Sure mam assign it to me. @SB2318
