### ISSUE TITLE
💡[Feature]: Integrate React Native TTS.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

*  **Install the Library:** 
First, you need to install the react-native-tts library

* Use it in the **PodcastScreen** with custom text 

* **Control Speech with Play Button:** Implement a function to handle the play button click, which will start or stop the speech:
![image](https://github.com/user-attachments/assets/77e41dfb-e163-42ad-a151-680a06e6416d)

* Control and display the speech progress, with the seekbar.
Track Speech Progress: Use the **Tts.addEventListener** to track the speech progress

![image](https://github.com/user-attachments/assets/a43a9f18-433e-42c1-a8e2-c08b6a34a435)

### Use Case

**App Feature & Logic Building**

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0c051982-e825-4849-8744-25a7df0bf616)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by dhairyagothi** [comment]
@SB2318 please assign this issue to me i can try this

**Comment by SB2318** [comment]
@dhairyagothi Please let me know your availability for the issue.

**Comment by dhairyagothi** [comment]
@SB2318 yes i am available

**Comment by dhairyagothi** [comment]
@SB2318 please assign someone else i have no experience in app development

**Comment by SB2318** [comment]
> @SB2318 please assign someone else i have no experience in app development

Okay, no issues. 😇 You can contribute in other issues, or can create yours.

**Comment by rushiii3** [comment]
@SB2318, assign me this task!

**Comment by SB2318** [comment]
> @SB2318, assign me this task!

No need to wait for the assignment now 😇, as the program is over. 🎉 If you feel you can contribute to something, then just start working and create a PR! 🚀

**Comment by rushiii3** [comment]
@SB2318, check discord

**Comment by rushiii3** [comment]
@SB2318, check discord
