### ISSUE TITLE
📝[Docs]: Audio File Contribution: Exercise And It's role to prevent diseases

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Source:  https://github.com/SB2318/UltimateHealth/blob/develop/DataSources/English/Exercise%20and%20Its%20Role%20in%20Preventing%20Diseases.md

### Suggested Change

You have to add the mp3 file in the datasource folder.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by ananyag309** [comment]
Please assign this issue to me
