### ISSUE TITLE
Kindly give a brief description about the project ?

### ISSUE THREAD

**Issue by Samarjiit** [SB2318/UltimateHealth#3]
Hi i am Samarjit. i have been learning react native since 2 months and i have a basic understanding of the react native. can you please provide some details about the project so that i can start as soon as possible or we can catch up over meet.

**Comment by Muskansahuincredible** [comment]
PLEASE ASSIGN ME THIS ISSUE I WILL REALLY WORK HARD ON IT

**Comment by SB2318** [comment]
@Muskansahuincredible Will get you back soon. 😇
Thanks for selecting this repo.

**Comment by SB2318** [comment]
@Samarjiit, Once the contribution process begins, will start a discussion over a meet-up. 
Keep Contributing!🎉
