### ISSUE TITLE
Design a SplashScreen and Integrate it with the project (Implement Stack Navigation)

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#30]
Design a **SplashScreen** and Integrate it with the project.

Your task will be first, to design a **SplashScreen** for the React-Native project, Followed by your need to implement the functionality.

Source: https://github.com/SB2318/UltimateHealth/blob/ultimate_health_frontend/src/Theme.js

Continuation of #14 

Start work, once issue no #14 will complete.

Thanks for your patience and keep contributing!

**Comment by BHS-Harish** [comment]
Hey @SB2318 

Let me design splash screen too, If you give me change.

Thanks in advance

**Comment by viththagi** [comment]
hey @SB2318 i would like to work on this issue. i just designed a splash screen for. this project thanks in advance
![iPhone 13 mini - 1](https://github.com/SB2318/UltimateHealth/assets/153849143/cde145f0-635a-4aa1-9d8d-d672d4d81d2e)
)

**Comment by SB2318** [comment]
> Hey @BHS-Harish, saw your PR on the logo design and would be happy implementing your SplashScreen design too if you would like to work on the design!

Share your points too.

**Comment by kylie-kiaying** [comment]
@SB2318 @BHS-Harish 

> > Hey @BHS-Harish, saw your PR on the logo design and would be happy implementing your SplashScreen design too if you would like to work on the design!
> 
> Share your points too.

I was initially thinking of having the logo at the center of the screen, with Ultimate Health below the logo, and there could be an animation whereby another heart of the same size drops down to where the position of the heart on the logo is in. I'm also happy to hear any other design ideas!

**Comment by SB2318** [comment]
@kylie-kiaying I appreciate your idea. ❤
If you need any kind of guidance, feel free to reach out to me. 😇👍

discord_server: susmita_

**Comment by BHS-Harish** [comment]
> Hey @BHS-Harish, saw your PR on the logo design and would be happy implementing your SplashScreen design too if you would like to work on the design!

No worries buddy @kylie-kiaying 
You can work on the issue

@SB2318  already said it's open source project so we should give opportunity to all contributors 😇

**Comment by SB2318** [comment]
@kylie-kiaying any update, Please check the message and respond. Your 5 days are over.

**Comment by BHS-Harish** [comment]
Hey @SB2318 

May i design the splash screen..?
But i don't know how do integrate with the project.

Assign to me, If @kylie-kiaying not responded.

Thanks in advance.

**Comment by SB2318** [comment]
> Hey @SB2318
> 
> May i design the splash screen..? But i don't know how do integrate with the project.
> 
> Assign to me, If @kylie-kiaying not responded.
> 
> Thanks in advance.
She can do it 😇, Please wait for the new issues.

**Comment by SB2318** [comment]
closed by #58
