### ISSUE TITLE
📝[Docs]: Rheumatoid Arthritis English & Hindi

### ISSUE THREAD

**Issue by revanth1718** [SB2318/UltimateHealth#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Rheumatoid arthritis (RA) is a long-term autoimmune disease that causes joint inflammation. It occurs when the immune system attacks its own tissues, and can affect any joint in the body, but is most common in the hands, wrists, feet, ankles, knees, shoulders, and elbows.

I think everyone should get aware of this 

I want to write the article on this topic. @SB2318 kindly assign me this issue under GSSOC

### Suggested Change

NA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by revanth1718** [comment]
@SB2318, assign me this issue

**Comment by revanth1718** [comment]
@SB2318, assign me this issue

**Comment by SB2318** [comment]
@revanth1718 Please provide both Hindi & English translation
