### ISSUE TITLE
💡[Feature]: Filter Page Implementaion in frontend

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

https://www.figma.com/design/TJ4s3xBpRwoZJCUHzQ2yhY/Filter-Page?node-id=0-1&t=XjePvGFIoFZGZT3x-0

### Use Case

Feature

### Benefits

App

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@rushiii3 would u like to work on this?

**Comment by rushiii3** [comment]
Sure!

**Comment by rushiii3** [comment]
@SB2318 , Review this PR; if you need changes, please do so. #334

**Comment by SB2318** [comment]
> @SB2318 , Review this PR; if you need changes, please do so. #334

okay, will  check.
