### ISSUE TITLE
📝[Docs]:  Understanding Genetic Disorders and the incidence of genetic-based health disorders (Easy to understand)

### ISSUE THREAD

**Issue by Damini2004** [SB2318/UltimateHealth#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Medical genetics and the incidence of genetic-based health disorders.

### Suggested Change

Medical genetics and the incidence of genetic-based health disorders.

### Rationale

Medical genetics and the incidence of genetic-based health disorders.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@Damini2004
