### ISSUE TITLE
 Benefits of Yoga for Mental and Physical Health

### ISSUE THREAD

**Issue by Aditijainnn** [SB2318/UltimateHealth#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

yoga and meditation have become increasingly popular in recent years, and for good reason. These practices have been shown to have a wide range of benefits for both physical and mental health. 

### Use Case

From reducing stress and anxiety to improving flexibility and balance, the benefits of yoga and meditation are numerous.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Nice

**Comment by SB2318** [comment]
@Aditijainnn good topic! please contribute english & hindi translation with your PR
