### ISSUE TITLE
📝[Docs]: Myeloma English & Hindi

### ISSUE THREAD

**Issue by sreevidya-16** [SB2318/UltimateHealth#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Myeloma, also known as multiple myeloma or plasma cell myeloma, is a type of cancer that develops in the **bone marrow** from abnormal **plasma cells**.

I want to add some topics like
- Causes
- Symptoms
- Survival Rate
- Is it Curable ?
- Rare or frequent ?
- Preventive measures
- Treatment

@SB2318, assign me this issue under GSSOC'24

### Suggested Change

NA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sreevidya-16** [comment]
@SB2318, assign me this issue

**Comment by SB2318** [comment]
@sreevidya-16 Please provide both english & Hindi translation

**Comment by sreevidya-16** [comment]
Sure @SB2318 mam
