### ISSUE TITLE
Automated Greeting Workflow using Github Bots

### ISSUE THREAD

**Issue by sanmarg** [SB2318/UltimateHealth#33]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet(using Github Bots) users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

**Comment by SB2318** [comment]
Sure! You can give it a try.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by SB2318** [comment]
closes #45
