### ISSUE TITLE
📝[Docs]:  ADHD Documentation in hindi and english

### ISSUE THREAD

**Issue by Damini2004** [SB2318/UltimateHealth#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

ADHD Documentation in hindi and english

### Suggested Change

ADHD Documentation in hindi and english

### Rationale

ADHD Documentation in hindi and english

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Nice topic @Damini2004 ! Please go with it.
