### ISSUE TITLE
💡[Feature]: Replace any with proper type, & use NativeStackScreenProps 

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Whenever Prop Is required, you have to define that props for the particular screen (Until we replace props drilling with redux)
Create Type for each object (Whenever it is required)
Add all the datatype inside **type.ts** file.

https://github.com/SB2318/UltimateHealth/blob/develop/frontend/src/type.ts

### Use Case

OOPs

### Benefits

Feature

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by SB2318** [comment]
@rushiii3

**Comment by rushiii3** [comment]
Okayy

**Comment by rushiii3** [comment]
@SB2318, you can assign me!

**Comment by rushiii3** [comment]
@SB2318, check if any changes are needed. #438
