### ISSUE TITLE
📝[Docs]: "Living with COPD: Tips for a Better Quality of Life"

### ISSUE THREAD

**Issue by arunimaChintu** [SB2318/UltimateHealth#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Living with COPD: Tips for a Better Quality of Life

### Suggested Change

Living with COPD: Tips for a Better Quality of Life

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Similar article available
