### ISSUE TITLE
📝[Docs]: "Understanding Multiple Sclerosis: Symptoms, Diagnosis, and Treatment"

### ISSUE THREAD

**Issue by arunimaChintu** [SB2318/UltimateHealth#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Understanding Multiple Sclerosis: Symptoms, Diagnosis, and Treatment

### Suggested Change

Understanding Multiple Sclerosis: Symptoms, Diagnosis, and Treatment

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Nice topic!

**Comment by Pujan-sarkar** [comment]
@SB2318 please assign this issue too
