### ISSUE TITLE
📝[Docs]: The Role of Diet and Nutrition in Managing Osteoarthritis

### ISSUE THREAD

**Issue by Nayanika1402** [SB2318/UltimateHealth#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

How certain foods can help reduce inflammation and improve joint health and also how one can avoid knee replacement surgeries with proper maintainance of diet.

### Suggested Change

New Addition.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@Nayanika1402 provide hindi & english translation

**Comment by Nayanika1402** [comment]
@SB2318 Okay I will do so.
