### ISSUE TITLE
🐞[Bug]: Autocommenting feature on an issue opening. Not enabled every time

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/b8e09a53-0ddb-4bec-838d-a6afc82cd2fb)

### Expected behavior

The GitHub bot should comment on every new issue to inform contributors that their issue is being addressed.

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.
