### ISSUE TITLE
📝[Docs]: Create New Pull Request Template.

### ISSUE THREAD

**Issue by PradnyaGaitonde** [SB2318/UltimateHealth#38]
Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

**Comment by SB2318** [comment]
I think, as of now it is not needed. But we can try something else, like If you want you can work on creating a template for Pull Request.

This will be a great issue, you can specify the things, like what type of contributions one has made, In which category it belongs, like feature or bug, 

You can refer to this repo and can set up your ideas.

https://github.com/ihridoydas/BaseTemplateAndroidApp.

Let me know If you are interested in taking this responsibility, and I will assign this issue to you after a little bit of modification.

**Comment by PradnyaGaitonde** [comment]
@SB2318 Yeah sure, this is a great issue and I am willing to do this. Please assign this issue to me.
