### ISSUE TITLE
📝[Docs]: "Tuberculosis Unveiled: The Evolution of Modern Treatments"

### ISSUE THREAD

**Issue by arunimaChintu** [SB2318/UltimateHealth#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Tuberculosis Unveiled: The Evolution of Modern Treatments

### Suggested Change

Tuberculosis Unveiled: The Evolution of Modern Treatments

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Nice!
