### ISSUE TITLE
📝[Docs]: "Sarcoidosis Secrets: Understanding This Rare Lung Disease"

### ISSUE THREAD

**Issue by arunimaChintu** [SB2318/UltimateHealth#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Sarcoidosis Secrets: Understanding This Rare Lung Disease

### Suggested Change

Sarcoidosis Secrets: Understanding This Rare Lung Disease

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
