### ISSUE TITLE
📝[Docs]: "Crohn’s Disease Chronicles: Managing Flare-Ups and Maintaining Health"

### ISSUE THREAD

**Issue by arunimaChintu** [SB2318/UltimateHealth#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Crohn’s Disease Chronicles: Managing Flare-Ups and Maintaining Health

### Suggested Change

Crohn’s Disease Chronicles: Managing Flare-Ups and Maintaining Health

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pujan-sarkar** [comment]
@SB2318 I am working on this issue , please assign me this .
