### ISSUE TITLE
📝[Docs]: The Science Behind Plant-Based Diets:

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Delve into the nutritional benefits of a plant-based diet, including the role of essential nutrients and how to ensure a balanced intake.

### Suggested Change

I will add this in a very structured way
@SB2318  please assign this to me under GSSOC 😊

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@Utsavladia would you like to contribute in it?

**Comment by Utsavladia** [comment]
@SB2318 
Sure

**Comment by Utsavladia** [comment]
There is some error due to which clone is not working properly
![image](https://github.com/user-attachments/assets/50eba695-5906-4ccc-b39f-9937cd0630c2)


Kindly suggest me if there is any other setup i need to do 
I forked unchecking the only main option as mentioned

**Comment by SB2318** [comment]
> Author

wait, some  files are making issue, let me find those guys with their PRs😂, will decrease all their level.

**Comment by Utsavladia** [comment]
okay 😂
There would be among some last merges cuz I think after that i am the first to raise this issue...

**Comment by Utsavladia** [comment]
ALso let me know any other topics If you want i can raise issue for them cuz i wanna contribute to this before the GSSOC ends and  be in stay in top 50 contributor till the end 😁

**Comment by SB2318** [comment]
> @SB2318 okay 😂 There would be among some last merges cuz I think after that i am the first to raise this issue...

No issues! I always appreciate the effort the contributors are making from my side. 😇

**Comment by SB2318** [comment]
> ALso let me know any other topics If you want i can raise issue for them cuz i wanna contribute to this before the GSSOC ends and stay in top 50 contributor till the end 😁

sure! My pleasure! You can raise the issue on your own. 😇

**Comment by SB2318** [comment]
> @SB2318 There is some error due to which clone is not working properly ![image](https://private-user-images.githubusercontent.com/124615886/355736637-50eba695-5906-4ccc-b39f-9937cd0630c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzE1NjksIm5iZiI6MTcyMzAzMTI2OSwicGF0aCI6Ii8xMjQ2MTU4ODYvMzU1NzM2NjM3LTUwZWJhNjk1LTU5MDYtNGNjYy1iMzlmLTk5MzdjZDA2MzBjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMTQ3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTdiYWMwZmViNTIyMmVkMmQ3MTc4MjNlYWE2OTYzNTE2ZWFlZTYzYzM3YjgxOTdlMjY3ZmM3ZjNiM2JjNDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EN_VkWynHk85Msr6Q6qx7f0wFFAve1z4BR3Jeir-ArU)
> 
> Kindly suggest me if there is any other setup i need to do I forked unchecking the only main option as mentioned

Thanks for informing me.
You can start work! 😇

![image](https://github.com/user-attachments/assets/6a6ab3f8-3b51-4be1-bd79-763039f1273b)

**Comment by Utsavladia** [comment]
> > ALso let me know any other topics If you want i can raise issue for them cuz i wanna contribute to this before the GSSOC ends and stay in top 50 contributor till the end 😁
> 
> sure! My pleasure! You can raise the issue on your own. 😇

You seems to be very nice person 😌
Kindly reivew this one and then i'll create new interesting topics if everything goes well...

**Comment by SB2318** [comment]
> > > ALso let me know any other topics If you want i can raise issue for them cuz i wanna contribute to this before the GSSOC ends and stay in top 50 contributor till the end 😁
> > 
> > 
> > sure! My pleasure! You can raise the issue on your own. 😇
> 
> You seems to be very nice person 😌 Kindly reivew this one and then i'll create new interesting topics if everything goes well...

Thank you for your kind words! 😇 I will review and merge soon. In the meantime, please enjoy the GSSOC Live program! 😇🥳

**Comment by Utsavladia** [comment]
@SB2318 
Thank you.. I have created issues for new interesting topics.
