### ISSUE TITLE
Brief introduction about the project

### ISSUE THREAD

**Issue by rushiii3** [SB2318/UltimateHealth#4]
Hi @SB2318, I'm eager to contribute to the project. Could you provide more details about it?

**Comment by SB2318** [comment]
@aryadavare19 Java is the root of Android Development.  
Don't worry. Start Contributing, Keep patience.

**Comment by SB2318** [comment]
> Hi @SB2318, I'm eager to contribute to the project. Could you provide more details about it?

@rushiii3 Keep Patience. We will update the repo soon.
