### ISSUE TITLE
📝[Docs]: The Benefits of Intermittent Fasting 

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This documentation will include the benifits of fasting a while 

### Suggested Change

Add new documents

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Sorry @Utsavladia, Similar article available.
