### ISSUE TITLE
📝[Docs]: Cluster Knowledge on Genetic Diseases: Prevention and Maintenance Strategies

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This wil include the role of our genetics on the overall health and diseases

### Suggested Change

New documentation

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
@Utsavladia
