### ISSUE TITLE
📝[Docs]: "Creatinine Levels and Dialysis: When is Treatment Necessary?"

### ISSUE THREAD

**Issue by arunimaChintu** [SB2318/UltimateHealth#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Creatinine Levels and Dialysis: When is Treatment Necessary?

### Suggested Change

Creatinine Levels and Dialysis: When is Treatment Necessary?

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pujan-sarkar** [comment]
@SB2318 I am working on this issue please assign me this .
