### ISSUE TITLE
📝[Docs]: "When to See a Doctor for Swimmer's Ear"

### ISSUE THREAD

**Issue by arunimaChintu** [SB2318/UltimateHealth#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

When to See a Doctor for Swimmer's Ear

### Suggested Change

When to See a Doctor for Swimmer's Ear

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Good Topic! You can start
