### ISSUE TITLE
📝[Docs]: How Your Digestive System Affects Mental Health

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This will add article on how our digestive system affect mental health

### Suggested Change

Add new documentation 

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Yes, Good topic! You can start work!
