### ISSUE TITLE
📝[Docs]: Advances in Immunotherapy for Cancer Treatment

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This will add article about one of the cancer therapy

### Suggested Change

add new documentation

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Issue Description
> This will add article about one of the cancer therapy
> 
> ### Suggested Change
> add new documentation
> 
> ### Rationale
> _No response_
> 
> ### Urgency
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Nice! You can start work on it. 😇
