### ISSUE TITLE
💡[FEATURE]: Implement Bottom Tab Navigation In Mobile App

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#42]
**Additional context**

 Here You have to implement **react-tab** navigation.
Libraries : 
(i) [@react-navigation/bottom-tabs](https://github.com/react-navigation/react-navigation/tree/main/packages/bottom-tabs):
(ii) https://www.npmjs.com/package/react-native-vector-icons

You need to integrate those two libraries inside the frontend project.

Create three screen **(Home, Podcasts, Profile)** (Icon will be **react-native-vector-icons**)

Attach those screens with a tab.

### Your workspace:

** Create a new folder **

`./frontend/src/navigations/TabNavigation`

Inside the **TabNavigation** Screen, Implement the **TabNavigation** code.

**Create Screens**

All three screens will be located at

./frontend/src/screens Package.

**Integrate your code in the main app component.**

For any queries feel free to reach out to me at the discord server and please message me with your issue ID.

**Comment by rushiii3** [comment]
Hey @SB2318, i would like to try this assign me this issue

**Comment by SB2318** [comment]
@adrikaDwivedi As the issues are first come first serve basis, Don't worry, Please stay tuned with the project.

**Comment by SB2318** [comment]
#46
