### ISSUE TITLE
📝[Docs]: Plague

### ISSUE THREAD

**Issue by revanth1718** [SB2318/UltimateHealth#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I want to add brief introduction on the topic "Plague"

- Historical Overview of the Plague
- The Biology of Yersinia pestis
- Plague Transmission and Spread
- Modern Plague Outbreaks
- Plague Prevention and Control Measures
- The Impact of Plague on Medieval Europe
- Plague and Its Influence on Literature and Art
- Plague vs. Other Infectious Diseases
- The Role of Plague in Shaping Public Health Policies
- Plague in the Americas: Historical and Modern Perspectives
- The Role of Plague in Biological Warfare
- The Plague and Climate Change

- Plague Treatment and Medical Advances

@SB2318 assign me this issue

### Suggested Change

NA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Nice!
