### ISSUE TITLE
📝[Docs]: Anxiety and Obsessive Compulsive Disorder.

### ISSUE THREAD

**Issue by Damini2004** [SB2318/UltimateHealth#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Anxiety and Obsessive Compulsive Disorder.

### Suggested Change

Anxiety and Obsessive Compulsive Disorder.

### Rationale

Anxiety and Obsessive Compulsive Disorder.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Similar content available.
