### ISSUE TITLE
📝[Docs]: Polio 

### ISSUE THREAD

**Issue by Maheshwari-Love** [SB2318/UltimateHealth#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Polio, caused by the poliovirus, was once a feared disease causing paralysis and death worldwide. The development of the polio vaccine by Jonas Salk in 1955 and later the oral vaccine by Albert Sabin significantly reduced its incidence.

### Suggested Change

Prevention: Vaccination remains the most effective prevention method. Global efforts continue to completely eradicate polio.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@SB2318 please assign me this task

**Comment by Maheshwari-Love** [comment]
@SB2318 i am getting error while pushing code 


PS D:\gssoc\UltimateHealth>     git push --set-upstream origin Add/Polio-prevention
remote: Permission to SB2318/UltimateHealth.git denied to Maheshwari-Love.
fatal: unable to access 'https://github.com/SB2318/UltimateHealth.git/': The requested URL returned error: 403

**Comment by SB2318** [comment]
> @SB2318 i am getting error while pushing code
> 
> PS D:\gssoc\UltimateHealth> git push --set-upstream origin Add/Polio-prevention remote: Permission to SB2318/UltimateHealth.git denied to Maheshwari-Love. fatal: unable to access 'https://github.com/SB2318/UltimateHealth.git/': The requested URL returned error: 403

fork the repo, you haven't edit access for main repo.
