### ISSUE TITLE
📝[Docs]:  Antimicrobial Resistance (AMR) understanding and preventions

### ISSUE THREAD

**Issue by Maheshwari-Love** [SB2318/UltimateHealth#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

AMR occurs when bacteria, viruses, fungi, and parasites evolve to resist the effects of medications, making infections harder to treat.

### Suggested Change

Prevention includes responsible use of antibiotics, promoting vaccination, improving infection prevention and control, and supporting research into new antimicrobials.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@SB2318 please assign me this task

**Comment by SB2318** [comment]
> @SB2318 please assign me this task

please also include your own view.
