### ISSUE TITLE
📝[Docs]:   Alzheimer’s Disease vs Dementia

### ISSUE THREAD

**Issue by Maheshwari-Love** [SB2318/UltimateHealth#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

First, provide an overview of dementia, but since content on Alzheimer’s Disease is already available, there’s no need for an overview of that specific condition. Then, proceed directly to the main topic.

### Suggested Change

While there is no definitive way to prevent Alzheimer’s, maintaining a healthy lifestyle, staying mentally active, and managing cardiovascular risk factors (like hypertension and diabetes) may reduce the risk.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@SB2318 please assign me this task

**Comment by SB2318** [comment]
> @SB2318 please assign me this task

First, provide an overview of dementia, but since content on Alzheimer’s Disease is already available, there’s no need for an overview of that specific condition. Then, proceed directly to the main topic.
