### ISSUE TITLE
📝[Docs]:  Missing learn.md file

### ISSUE THREAD

**Issue by adrikaDwivedi** [SB2318/UltimateHealth#44]
Learn repos should have a LEARN.md file to teach student how to build project step by step. One can explain how to build this project with text, code snippets, images etc.

The LEARN.md file requires to think critically about how to explain the building of this project and how to also make it engaging.

This issue would like to reflect on how difficult it was to get to level of knowledge executed, and then provide friendly guidance to help other contributors to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by SB2318** [comment]
Okay Great! you can start 👍

**Comment by SB2318** [comment]
@adrikaDwivedi If you need any discussion on this issue, feel free to reach out on the discord server, Please mention your issue id there.

**Comment by adrikaDwivedi** [comment]
Hey @SB2318  would like to connect and discuss about the project, where can I get your discord id ?

**Comment by SB2318** [comment]
> Hey @SB2318 would like to connect and discuss about the project, where can I get your discord id ?

@adrikaDwivedi Okay will connect tomorrow, Discord Id susmita_5116

**Comment by SB2318** [comment]
@adrikaDwivedi please join, your 5 days have already been over.

**Comment by SB2318** [comment]
@AnushkaSharma04 Your issue remains unassigned to everyone until you report me and also for next 7 days.
