### ISSUE TITLE
📝[Docs]: PCOD

### ISSUE THREAD

**Issue by sreevidya-16** [SB2318/UltimateHealth#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Polycystic Ovarian Disease (PCOD) is a hormonal imbalance and metabolic disorder that affects women of reproductive age.

I want to add article on this topic, it will be very useful for present generation girls and women.

@SB2318 assign me this topic

### Suggested Change

NA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
similar content available.
