### ISSUE TITLE
📝[Docs]: The Importance of Hydration: How Water Affects Every Aspect of Health.. all focus on water 👀

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This includs the importance of hydration in our daily life to keep us healthy 

### Suggested Change

Add new document

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
Nice!
