### ISSUE TITLE
📝[Docs]: Benefits of Yoga for mental and physical health (Spanish and Malay)

### ISSUE THREAD

**Issue by suhanipaliwal** [SB2318/UltimateHealth#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Benefits of Yoga for mental and physical health in Spanish and Malay

### Suggested Change

Benefits of Yoga for mental and physical health in Spanish and Malay.

### Rationale

Benefits of Yoga for mental and physical health in Spanish and Malay.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
