### ISSUE TITLE
💡[FEATURE]: Add One Notebook Icon On the HomeScreen

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#47]
**Describe the solution you'd like**

The Notebook icon feature is mainly responsible to land user to article writing page.

References:

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/e12c661a-fd0e-4914-abb9-6cbbb0bb87e5)

Replace '+' with note icon.

Make sure it will be there only for first tab screen.

Continuation of #42

**Comment by rushiii3** [comment]
Hey @SB2318 , i would like to do this issue.

**Comment by AnushkaSharma04** [comment]
@SB2318 Kindly assign this issue to me . I am a gssoc'24 contributor

**Comment by SB2318** [comment]
> @SB2318 Kindly assign this issue to me . I am a gssoc'24 contributor

Sure, Kindly wait for the completion of #42

**Comment by SB2318** [comment]
@AnushkaSharma04 any update?

**Comment by AnushkaSharma04** [comment]
@SB2318 Working on alignment

**Comment by SB2318** [comment]
> @SB2318 Working on alignment

@AnushkaSharma04 If you need any help, please reach out either on the project channel or to me.

**Comment by SB2318** [comment]
@AnushkaSharma04  Please join in the discord meeting at 8:30 today.

**Comment by SB2318** [comment]
@AnushkaSharma04 please join, your 5 days have already been over.

**Comment by SB2318** [comment]
@AnushkaSharma04 Your issue remains unassigned to everyone until you report me and also until the article module has started,

**Comment by nishant0708** [comment]
can you assign me this issue under gssoc 24.

**Comment by K-21** [comment]
@SB2318 can you assign me this issue under gssoc 24.

**Comment by divyesh-mali** [comment]
@SB2318 
I would like to work on this one. My question is, after landing the user to article writing page, do we also have to design a new page for that with all functionalities?

**Comment by SB2318** [comment]
> @SB2318 I would like to work on this one. My question is, after landing the user to article writing page, do we also have to design a new page for that with all functionalities?

Good questions, but we can't discuss it here

**Comment by SB2318** [comment]
> > @SB2318 I would like to work on this one. My question is, after landing the user to article writing page, do we also have to design a new page for that with all functionalities?
> 
> Good question, but we can't discuss it here, please wait for the upcoming issues

**Comment by Tejsvapandey1** [comment]
@SB2318 please mam assign me this issuee

**Comment by akshathere** [comment]
Hello @SB2318  I can do this task if you can assign me under GSSoc'24
