### ISSUE TITLE
📝[Docs]: Polycystic Ovary Syndrome (PCOS): Managing Symptoms and Enhancing Quality of Life (English)

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This will add article about the PCOS in English

### Suggested Change

New documentation

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Utsavladia** [comment]
@SB2318 
Should I work on the three last issues I have created to add them in the contributions as well...🙂

**Comment by SB2318** [comment]
evaluate this at a later time.
