### ISSUE TITLE
📝[Docs]: "The Impact of Birth Control on Hormonal Health: What You Need to Know"

### ISSUE THREAD

**Issue by Utsavladia** [SB2318/UltimateHealth#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This will add article on the birth control

### Suggested Change

New documentation

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
