### ISSUE TITLE
💡[FEATURE]: Design Login Screen

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#48]
**Describe the solution you'd like**

You have to design the LoginScreen, here is your prototype:

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/f2134a01-88cc-4116-a5f1-10d656197a31)

To get started, please follow these steps:

* Design the LoginScreen component based on the provided prototype.

* Implement the component in the App.tsx file for testing purposes.

* Make sure the LoginScreen component is located in the following folder: 
     `./frontend/src/screen/auth/LoginScreen.`
    
* Handle screen size dynamically, (Do not use any static value like height:80, width:20 or something like that)    
* Once you have completed the design and implementation, take a screenshot of the LoginScreen while the application is running.

* Finally, submit your changes by creating a Pull Request (PR) with the screenshot attached.

**Comment by rushiii3** [comment]
Hey @SB2318, i would like to give a try for this

**Comment by rushiii3** [comment]
Hey @SB2318, 
I'm thinking of creating a folder and a file `./frontend/src/helper/Metric.js` to the app's responsiveness. This would make it usable overall. 
Here is the reference link : [Create Responsive Design In React Native](https://medium.com/simform-engineering/create-responsive-design-in-react-native-f84522a44365)

**Comment by SB2318** [comment]
> Hey @SB2318, I'm thinking of creating a folder and a file `./frontend/src/helper/Metric.js` to the app's responsiveness. This would make it usable overall. Here is the reference link : [Create Responsive Design In React Native](https://medium.com/simform-engineering/create-responsive-design-in-react-native-f84522a44365)

@rushiii3 let me know whether project channel visible to you on the discord server?

**Comment by NaunihalSingh40** [comment]
Hi @joyhughes Naunihal Singh this side from Gssoc, making login page is a great task to do.
I request you to assign this task to me.

I will be glad to have this opportunity!

**Comment by rushiii3** [comment]
> @rushiii3 let me know whether project channel visible to you on the discord server?
No, the project channel is not visible to me. Could you please guide me on how to access it?

**Comment by SB2318** [comment]
@rushiii3 message me on my discord handle.

**Comment by SB2318** [comment]
@rushiii3 Hope my message has reached you, please come to the discord server at the mentioned time.

**Comment by SB2318** [comment]
> Hi @SB2318 Naunihal Singh this side from Gssoc, making login page is a great task to do. I request you to assign this task to me.
> 
> I will be glad to have this opportunity!

Hello @NaunihalSingh40 

You can explore the latest available issues. 😇

Keep Contributing!

**Comment by rushiii3** [comment]
Hey @SB2318, please update me when the fonts have been added.

**Comment by rushiii3** [comment]
**Here is the preview of login page in ios with dark mode and light mode** 
<img src="https://github.com/SB2318/UltimateHealth/assets/105168088/05d25392-8353-464e-973a-45db272d40e2" height="600" /> <img src="https://github.com/SB2318/UltimateHealth/assets/105168088/1143c3d4-ac5f-4b33-bba4-8f4770eb6a25" height="600" />


**Here is the preview of login page in android with dark mode and light mode** 
<img src="https://github.com/SB2318/UltimateHealth/assets/105168088/92c22d32-7483-4256-b11d-b42f7d35c426" height="600" /> <img src="https://github.com/SB2318/UltimateHealth/assets/105168088/dc5d9c8a-5a1b-4688-ba04-2c1f4c968615" height="600" />

**Comment by SB2318** [comment]
@rushiii3 Please raise your PR (Update your branch before).
