### ISSUE TITLE
📝[Docs]: When to See a Doctor for Swimmer's Ear (Spanish and Malay)

### ISSUE THREAD

**Issue by suhanipaliwal** [SB2318/UltimateHealth#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

When to See a Doctor for Swimmer's Ear in Spanish and Malay

### Suggested Change

When to See a Doctor for Swimmer's Ear in Spanish and Malay

### Rationale

When to See a Doctor for Swimmer's Ear in Spanish and Malay

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
