### ISSUE TITLE
📝[Docs]: Understanding Insomnia: Causes, Symptoms, and Solutions( in spanish, malay and tamil)

### ISSUE THREAD

**Issue by AsmitaMishra24** [SB2318/UltimateHealth#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Understanding Insomnia: Causes, Symptoms, and Solutions( in spanish, malay and tamil)

### Suggested Change

Understanding Insomnia: Causes, Symptoms, and Solutions( in spanish, malay and tamil)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AsmitaMishra24** [comment]
@SB2318, ma'am please assign this issue.

**Comment by AsmitaMishra24** [comment]
@SB2318, ma'am please I will make pr as soon as you assign it.

**Comment by SB2318** [comment]
evaluate this at a later time.
