### ISSUE TITLE
📝[Docs]: Effect of ECT treatment on mental and physical health( in spanish, malay and tamil)

### ISSUE THREAD

**Issue by AsmitaMishra24** [SB2318/UltimateHealth#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Effect of ECT treatment on mental and physical health( in spanish, malay and tamil)

### Suggested Change

Effect of ECT treatment on mental and physical health( in spanish, malay and tamil)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AsmitaMishra24** [comment]
@SB2318, ma'am please assign this issue

**Comment by AsmitaMishra24** [comment]
@SB2318, ma'am please assign me this issue.

**Comment by SB2318** [comment]
@AsmitaMishra24 Please select existing issue with gssoc level.
And make sure you can create PR before 7 pm.😊

**Comment by SB2318** [comment]
evaluate this at a later time.
