### ISSUE TITLE
📝[Docs]: Emerging Role of Liquid Biopsies in Cancer Diagnosis and Monitoring

### ISSUE THREAD

**Issue by Pujan-sarkar** [SB2318/UltimateHealth#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Liquid biopsies are gaining prominence in cancer diagnosis and monitoring as a minimally invasive alternative to traditional tissue biopsies. By analyzing circulating tumor DNA (ctDNA), RNA, or cancer cells in a patient's blood, liquid biopsies provide real-time insights into tumor genetics, helping to detect cancer early, monitor disease progression, and assess treatment response. This emerging technology offers the potential for more personalized and dynamic cancer care, though challenges such as sensitivity, specificity, and standardization need to be addressed for widespread clinical adoption.

### Suggested Change

I want to add a documentation on this topic.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pujan-sarkar** [comment]
@SB2318 can you please assign me this issue

**Comment by Pujan-sarkar** [comment]
@SB2318 please assign me this issue

**Comment by SB2318** [comment]
@Pujan-sarkar Comment on existing issue, tag with gssoc, and you can create pr within 2 hours.

**Comment by SB2318** [comment]
evaluate this at a later time.
