### ISSUE TITLE
📝[Docs]: The Impact of Microplastics on Human Health

### ISSUE THREAD

**Issue by Maana-Ajmera** [SB2318/UltimateHealth#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Microplastics, tiny plastic particles found in food, water, and air, are being studied for their potential health risks. They may cause inflammation and toxicity in the human body. Understanding their impact is crucial as they become increasingly prevalent.

### Suggested Change

NA

### Rationale

I want to add information on the the Impact of Microplastics on Human Health

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@SB2318 Please assign it to me

**Comment by SB2318** [comment]
evaluate this at a later time.
