### ISSUE TITLE
📝[Docs]: The Link Between Oral Health and Systemic Diseases

### ISSUE THREAD

**Issue by Maana-Ajmera** [SB2318/UltimateHealth#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Poor oral health can contribute to systemic diseases like diabetes and heart disease. Infections and inflammation in the mouth may impact overall health, making good dental care essential for preventing these conditions.

### Suggested Change

NA

### Rationale

I want to add information on The Link Between Oral Health and Systemic Diseases

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@SB2318 please assign it to me

**Comment by SB2318** [comment]
evaluate this at a later time.
