### ISSUE TITLE
📝[Docs]: Ehlers-Danlos Syndrome (EDS)

### ISSUE THREAD

**Issue by revanth1718** [SB2318/UltimateHealth#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

A group of connective tissue disorders characterized by hyper-flexible skin, joint instability, and fragile tissues.

@SB2318 assign me this issue

### Suggested Change

NA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
