### ISSUE TITLE
Adding signup,signin,logout,navigation functionality 

### ISSUE THREAD

**Issue by Sudhan22z265** [SB2318/UltimateHealth#5]
I have experience in react native so that i can start this project by adding authentication, navigation.
I am gssoc'24 contributor i can do this @SB2318 

### Please assign me this task

**Comment by rushiii3** [comment]
Hey @SB2318 , I'd like to contribute to creating a beautiful signup, signin design with robust authentication. Could you please assign me this?

**Comment by Noobham** [comment]
Hi @SB2318 , Can you please add how the folder structure or architecture should look , Making will not make us any confusion how jsx and css files of components should interact each other .

**Comment by tusharyadav11** [comment]
i would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality
@SB2318

**Comment by SB2318** [comment]
> i would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality @SB2318

@tusharyadav11 All tasks will be distributed equally among the contributors on  First Come First Serve basis, once contributions begin.  Keep Contributing! 🎉

**Comment by SB2318** [comment]
> Hi @SB2318 , Can you please add how the folder structure or architecture should look , Making will not make us any confusion how jsx and css files of components should interact each other .

Wii do. Keep Contributing! 🎉

**Comment by SB2318** [comment]
> Hey @SB2318 , I'm a GSSOC'24 contributor. I'd like to contribute to creating a beautiful signup, signin design with robust authentication. Could you please assign me this?


Okay, get back to you soon once the contributions begin. Keep Contributing! 🎉
