### ISSUE TITLE
💡[FEATURE]: Create Middleware, Make User Data Secure using JWT 

### ISSUE THREAD

**Issue by soham0005** [SB2318/UltimateHealth#50]

**Comment by soham0005** [comment]
Helllo @SB2318 , may i work on this issue? All the doctor related backend routes will be setup in this issue

**Comment by soham0005** [comment]
Will include protected route in this issue as well, also please assign the label of level as well for this issue @SB2318

**Comment by SB2318** [comment]
@soham0005 Keep patience!😇  Will discuss.
