### ISSUE TITLE
📝[Docs]: Asthma : Causes, Symptoms, and Management

### ISSUE THREAD

**Issue by AmruthaPariprolu** [SB2318/UltimateHealth#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Asthma : Causes, Symptoms, and Management

### Suggested Change

i want to add this

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AmruthaPariprolu** [comment]
@SB2318 pls assign me this task

**Comment by SB2318** [comment]
evaluate this at a later time.
