### ISSUE TITLE
📝[Docs]: Amyotrophic Lateral Sclerosis (ALS) (English, Hindi)

### ISSUE THREAD

**Issue by AsmitaMishra24** [SB2318/UltimateHealth#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I would like to request the addition of a new article on Amyotrophic Lateral Sclerosis (ALS) in english and hindi to our repository. ALS is a progressive neurodegenerative disease that affects nerve cells in the brain and spinal cord, leading to loss of muscle control and eventual paralysis. Given the importance and relevance of this topic, having a comprehensive and well-researched article on ALS will be valuable for our readers.

### Suggested Change

A well-researched and informative article on ALS that will educate and support individuals seeking information on this condition.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
