### ISSUE TITLE
📝[Docs]: Gastroenteritis

### ISSUE THREAD

**Issue by AmruthaPariprolu** [SB2318/UltimateHealth#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Inflammation of the stomach and intestines, often caused by viruses or bacteria, leading to symptoms like vomiting, diarrhea, and abdominal pain.

### Suggested Change

i want to add this

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AmruthaPariprolu** [comment]
@SB2318 pls assign me this task

**Comment by SB2318** [comment]
evaluate this at a later time.
