### ISSUE TITLE
📝[Docs]: Tay-Sachs Disease

### ISSUE THREAD

**Issue by sreevidya-16** [SB2318/UltimateHealth#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Tay-Sachs disease (TSD) is a rare, inherited, and fatal genetic disorder that affects the nervous system and causes nerve cell destruction in the brain and spinal cord

I want to add article on this topic

@SB2318 assign me this issue under GSSOC'24

### Suggested Change

NA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sreevidya-16** [comment]
@SB2318 assign me this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
