### ISSUE TITLE
📝[Docs]: Cystic Fibrosis (Spanish and Malay)

### ISSUE THREAD

**Issue by suhanipaliwal** [SB2318/UltimateHealth#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Cystic Fibrosis (Spanish and Malay)

### Suggested Change

Cystic Fibrosis (Spanish and Malay)

### Rationale

Cystic Fibrosis (Spanish and Malay)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SB2318** [comment]
evaluate this at a later time.
