### ISSUE TITLE
💡[Feature]: Design a Beautiful Loader Animation relevant to app theme

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Loader for API Data Loading 

### Use Case

* API Data Loading
* Internet Connection Check

### Benefits

Application Feature

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by rushiii3** [comment]
@SB2318, we can use lottie animations.

**Comment by SB2318** [comment]
> @SB2318, we can use lottie animations.

Yes,  you can also use reanimated.

**Comment by rushiii3** [comment]
@SB2318, let me know if this works better.
[Loading Animated SVG](https://lottiefiles.com/free-animation/teal-healthy-heart-UjDmqut8Jz)
[Network Connection SVG](https://lottiefiles.com/free-animation/phone-wifi-mobile-internet-network-wifi-communication-connection-smartphone-animation-OAhMhVoEMG)

**Comment by SB2318** [comment]
> @SB2318, let me know if this works better. [Loading Animated SVG](https://lottiefiles.com/free-animation/teal-healthy-heart-UjDmqut8Jz) [Network Connection SVG](https://lottiefiles.com/free-animation/phone-wifi-mobile-internet-network-wifi-communication-connection-smartphone-animation-OAhMhVoEMG)

Keep it simple for loading: [Loading Animation](https://lottiefiles.com/free-animation/loading-c5cJgxLvtS)

Try to find our app theme color version of this. 👍
 
**Network Connection SVG** is good, you can use that.

**Comment by SB2318** [comment]
> @SB2318, let me know if this works better. [Loading Animated SVG](https://lottiefiles.com/free-animation/teal-healthy-heart-UjDmqut8Jz) [Network Connection SVG](https://lottiefiles.com/free-animation/phone-wifi-mobile-internet-network-wifi-communication-connection-smartphone-animation-OAhMhVoEMG)

You can also use this : https://lottiefiles.com/free-animation/vitay-animacion-ywGDSKgK7J

But, try to find this loader with **U** alphabet.

**Comment by rushiii3** [comment]
@SB2318, how about this 
[U alphabet ](https://lottiefiles.com/free-animation/up-logo-3g7e7m68Ew)

**Comment by SB2318** [comment]
> @SB2318, how about this [U alphabet ](https://lottiefiles.com/free-animation/up-logo-3g7e7m68Ew)

![image](https://github.com/user-attachments/assets/04f2842c-a783-4844-a62f-3f8e999886b4)

**Comment by SB2318** [comment]
> > @SB2318, let me know if this works better. [Loading Animated SVG](https://lottiefiles.com/free-animation/teal-healthy-heart-UjDmqut8Jz) [Network Connection SVG](https://lottiefiles.com/free-animation/phone-wifi-mobile-internet-network-wifi-communication-connection-smartphone-animation-OAhMhVoEMG)
> 
> Keep it simple for loading: [Loading Animation](https://lottiefiles.com/free-animation/loading-c5cJgxLvtS)
> 
> Try to find our app theme color version of this. 👍
> 
> **Network Connection SVG** is good, you can use that.

Or keep it simple like this. no need to change the color.😇

**Comment by rushiii3** [comment]
Which one should I choose?

**Comment by SB2318** [comment]
> Which one should I choose?

https://lottiefiles.com/free-animation/loading-c5cJgxLvtS

**Comment by rushiii3** [comment]
Okay

**Comment by rushiii3** [comment]
@SB2318, let me know if need changes #542
