### ISSUE TITLE
💡[FEATURE]: Refresh Token Functionality

### ISSUE THREAD

**Issue by soham0005** [SB2318/UltimateHealth#56]
As the JWT token will expire after specific duration, instead of login to get a new token, we can have route which will return us the new JWT token which will be valid for the user without explicitly logging into the system

Reference: 

(i) https://fusionauth.io/docs/apis/jwt#:~:text=The%20refresh%20token%20that%20can,is%20registered%20to%20the%20application.

(ii) https://www.geeksforgeeks.org/jwt-authentication-with-refresh-tokens/

(iii) https://stackoverflow.com/questions/27726066/jwt-refresh-token-flow

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/adda0ab9-b76e-47a6-abf7-5efdfb828a38)

@komalverma04  Please follow these articles, and ping me in discord I will share you the entire flow.

**Comment by soham0005** [comment]
Hello @SB2318 , Can i work on this feature?

**Comment by SB2318** [comment]
> Hello @SB2318 , Can i work on this feature?

It is good to have some kind of functionality, like after a particular time your session will expire and you need to log in again.

In that case, we can increase the session interval, but I am keeping this issue as hold as of now. Thanks for pointing out the feature! 😇

**Comment by komalverma04** [comment]
I want to work on this issue.

**Comment by soham0005** [comment]
@SB2318, is this issue still on hold? is there any other thing in backend that I can work on?

**Comment by SB2318** [comment]
> @SB2318, is this issue still on hold? is there any other thing in backend that I can work on?

Okay, you can start.

**Comment by SB2318** [comment]
@soham0005 any update?

**Comment by SB2318** [comment]
@komalverma04 are u available for this task?

**Comment by komalverma04** [comment]
> @komalverma04 are u available for this task?

Yes

**Comment by SB2318** [comment]
@komalverma04  any update?

**Comment by komalverma04** [comment]
> @komalverma04 any update?

I'll complete it by tomorrow

**Comment by komalverma04** [comment]
> > @komalverma04 any update?
> 
> I'll complete it by today

**Comment by SB2318** [comment]
> > > @komalverma04 any update?
> > 
> > 
> > I'll complete it by today

Okay, Sounds good!

**Comment by komalverma04** [comment]
@SB2318 I need some help!!

**Comment by SB2318** [comment]
> @SB2318 I need some help!!

do you want to connect now or tomorrow.

**Comment by komalverma04** [comment]
> > @SB2318 I need some help!!
> 
> do you want to connect now or tomorrow?

can we connect tomorrow ?

**Comment by SB2318** [comment]
> > > @SB2318 I need some help!!
> > 
> > 
> > do you want to connect now or tomorrow?
> 
> can we connect tomorrow ?

Okay, please ping in the project channel or discord.

**Comment by SB2318** [comment]
@komalverma04, 😔 I deeply apologize for any inconvenience caused, but it seems that there have been some changes in the authentication functionality. As a result, this functionality is no longer required. However, I have some exciting news for you! 🎉 There are new issues available, and your contribution would be greatly appreciated. I hope you can find joy and fulfillment in tackling these new challenges. Thank you for your understanding and continued support. 🙏
