### ISSUE TITLE
💡[FEATURE]: Design Signup Module

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#61]
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/f8afabd0-36ce-438d-96ef-2ef119a68eee)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/3648b893-4706-44ad-a491-668f7f28771b)

### Instructions:

* Use **react-native-vector-icons** as much as possible.
* Give Password **show-hide** feature.
* For **Doctor's Specialization**  part as of now create a static list with 5 types, and attach the list with **dropdown.**
     example :[ "Cardiology", "Dermatology", "Pediatrics"]
* Differ the text and numbers edit-text field.

**Figma file** will provided in person, if needed.

**Comment by MaryamMohamedYahya** [comment]
Please assign this to me as soon as the prototype is ready

**Comment by rushiii3** [comment]
hey @SB2318, i would like to do this task.

**Comment by ParthNakum21** [comment]
Hello @SB2318, I'm interested in contributing to the project by designing Sign Up page. Could you please assign this task to me under GSSoC with appropriate level?

**Comment by SB2318** [comment]
@MaryamMohamedYahya  are you ready to take this task?

**Comment by MaryamMohamedYahya** [comment]
> @MaryamMohamedYahya are you ready to take this task?

Yes

**Comment by SB2318** [comment]
@MaryamMohamedYahya  any update?

**Comment by SB2318** [comment]
@ParthNakum21  would you like to work on this task?

**Comment by ParthNakum21** [comment]
> @ParthNakum21 would you like to work on this task?

Yes, I am ready to work on this issue.

**Comment by SB2318** [comment]
@ParthNakum21 please reach out if you face any difficulty with the issue.

**Comment by ParthNakum21** [comment]
> @ParthNakum21 please reach out if you face any difficulty with the issue.

Thank you, Working on it!

**Comment by SB2318** [comment]
@ParthNakum21 update me.

**Comment by ParthNakum21** [comment]
Hello @SB2318, I am encountering some issues with starting the project. I have gone through the Readme file and also some articles to solve this, but I failed. Would you be able to assist me with this?

**Comment by SB2318** [comment]
> Hello @SB2318, I am encountering some issues with starting the project. I have gone through the Readme file and also some articles to solve this, but I failed. Would you be able to assist me with this?

okay, please share your discord_id

**Comment by ParthNakum21** [comment]
> > Hello @SB2318, I am encountering some issues with starting the project. I have gone through the Readme file and also some articles to solve this, but I failed. Would you be able to assist me with this?
> 
> okay, please share your discord_id

Discord ID: parthnakum21
