### ISSUE TITLE
💡[FEATURE]: Design Forgot Password module

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#62]
**Describe the solution you'd like**

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/eac667d6-cebb-4129-a3fd-37c347703972)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/e76a5ff4-7fcc-42f5-8834-1cee2edc8fae)

### Task Area:

* **EmailInputModal**  (`./frontend/src/components/EmailInputModal.tsx`)
*  **LoginScreen** (`./frontend/src/screens/auth/LoginScreen.tsx`)
*  **OtpScreen**  (`./frontend/src/screens/auth/OtpScreen.tsx`)
*  **NewPasswordScreen** ((`./frontend/src/screens/auth/NewPasswordScreen.tsx`)

@Hemu21  Please check the design changes.

**Comment by rushiii3** [comment]
Hey @SB2318, i would like to do this task.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@SB2318 Sir, I would really like to work on this issue under Gssoc'24, so please assign it to me.

**Comment by SB2318** [comment]
> Thank you @SB2318 Sir, for entrusting on me. Thank you for assigning this task to me.
Welcome to the Open source program 😇🥳
Please contact, me once your design task is over, And if you have some doubts feel free to reach out.

**Comment by SB2318** [comment]
@cpratik1307  any update?

**Comment by SB2318** [comment]
@rushiii3 Would you like to work on this task?

**Comment by cpratik1307** [comment]
> @cpratik1307  any update?

Still Working on it ...

**Comment by SB2318** [comment]
> > @cpratik1307  any update?
> 
> Still Working on it ...

are you facing any problem, see it is simple like web page design. And it doesn't need that much time, let me know if you need any resource.

**Comment by Hemu21** [comment]
@SB2318  can you please assign this to me
