### ISSUE TITLE
💡[FEATURE]:  Applying Fonts to Text in React Native

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#65]
**Describe the solution you'd like**

Your task is to integrate 2-3  types of font with frontend application.

Reference: 
https://medium.com/@prathiba2796/how-to-add-and-use-custom-fonts-in-react-native-369d5bba9203

Make sure the fonts work perfectly in the text.

**Task Example**

Use **Lobster** font for **App-Name**

There are more than two screens, where you can find the app name used.

**Additional context**

Please attach a snapshot of your changes with PR.

For any doubts or stuck situation related the task, feel free to reach out to me.

**Comment by rushiii3** [comment]
Hey @SB2318, i would like to do this task.
