### ISSUE TITLE
🪲[Bug]: Seamless User Experience: Eliminating SplashScreen Return : Handle System back button

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#66]
Users should never return to SplashScreen.

**Screenshots**

https://github.com/SB2318/UltimateHealth/assets/87614560/ba33aeb0-42c1-493c-bcdc-1b848c8f88d8

**Comment by sidharth2829** [comment]
Please assign this issue to me under gssoc'24

**Comment by SB2318** [comment]
> Please assign this issue to me under gssoc'24

Please join in the discord meeting at 8:30, before starting your work.

**Comment by SB2318** [comment]
@sidharth2829 any update?

**Comment by sidharth2829** [comment]
I have successfully build and launched the application on developer studio, but since ios devices dont have back buttons, i have tried disabling swipegesture on navigation tab and login screen

**Comment by SB2318** [comment]
> I have successfully build and launched the application on developer studio, but since ios devices dont have back buttons, i have tried disabling swipegesture on navigation tab and login screen

I think in IOS there will be something back gesture, you can try to set some **navigationOptions** for particularly that page.

For your reference:
(i) https://github.com/react-navigation/react-navigation/issues/9027
(ii) https://stackoverflow.com/questions/49821052/how-to-handle-the-back-button-on-ios-when-using-a-react-navigation-drawer

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/8f39547c-b67f-465e-9aac-86f66e89e8d4)

Please try with these options, If not work, then will discuss soon, currently weather is not good.

**Comment by sidharth2829** [comment]
ok

**Comment by sidharth2829** [comment]
https://github.com/SB2318/UltimateHealth/assets/111569459/897afce8-2bc4-45b6-95ee-7b74e95045bb

As you can see, i can't swipe back to splashscreen as swipe gesture is disabled on navigation tab

**Comment by sidharth2829** [comment]
@SB2318 , i have tried launching it on android but some system path variables and libraries are creating too much problems. Can you unassign me this task. And i also apologize for the delay happened because of me.

**Comment by SB2318** [comment]
> @SB2318 , i have tried launching it on android but some system path variables and libraries are creating too much problems. Can you unassign me this task. And i also apologize for the delay happened because of me.

share your discord id here

**Comment by sidharth2829** [comment]
discord id: sidharth_grover
