### ISSUE TITLE
Please give tell us how chat bot will be function? 

### ISSUE THREAD

**Issue by ArtiGaund** [SB2318/UltimateHealth#7]
I want to create chat bot for this application, which will help the user to identify the health problem?

**Comment by Muskansahuincredible** [comment]
PLEASE ASSIGN ME THIS ISSUE I WILL REALLY WORK HARD ON IT

**Comment by SB2318** [comment]
@ArtiGaund  Welcome to **GSSOC**  🎉.
 Thanks for selecting this project, will get back to you soon and will hear your ideas once the contribution begins. 😇

**Comment by SB2318** [comment]
> PLEASE ASSIGN ME THIS ISSUE I WILL REALLY WORK HARD ON IT

@Muskansahuincredible Great to hear that. ❤️
Okay, will get back to you soon once the contribution begins. 

Keep contributing!
