### ISSUE TITLE
Centralised/Single file for API calls in Backend

### ISSUE THREAD

**Issue by jaickeyminj** [SB2318/UltimateHealth#73]
**Current Situation**
Multiple files for routing listed below:

![image](https://github.com/SB2318/UltimateHealth/assets/95216865/3aa0f957-7047-4485-a1d0-8770a8620513)
![image](https://github.com/SB2318/UltimateHealth/assets/95216865/6b99172e-9645-47dc-bc25-c6c907a5ae8c)
![image](https://github.com/SB2318/UltimateHealth/assets/95216865/f1c6914b-c82d-4279-8655-4cafe538235a)

**My suggestion** 

In the backend folder, there is a `routes` folder designed to manage API calls. A **single file** within this folder should be created to handle the routing. The file uses Express.js to define routes for patient signup and other functionalities. It imports the necessary controllers and middleware to handle the requests.

Here’s a brief overview of the file:

- **Dependencies**: Imports Express.js, Router, and a middleware (Multer).
- **Controllers**: Imports specific functions (`patientSignup`, `patientLogin`, `updatePatientData`, `validateTokenPatient`) from the `patientAuth` controller.
- **Routes**: Defines routes for patient login and signup:
  - `POST /patient/login`: Handles patient login.
  - `POST /patient/signup`: Handles patient signup.
- **Export**: Exports the configured router to be used in the main application.

**This setup modularizes the routing logic, making the code more maintainable and scalable.**

![image](https://github.com/SB2318/UltimateHealth/assets/95216865/d972d823-382f-4cec-978b-55b0a29b3ed7)
![image](https://github.com/SB2318/UltimateHealth/assets/95216865/3f60dbfd-4692-48e6-90a4-6cf5632d7613)

**Comment by jaickeyminj** [comment]
@SB2318 

Please look into this

**Comment by SB2318** [comment]
@jaickeyminj  Both did the same thing,
Only here @Contributors named the file as **userRoute** instead of user

**Comment by meghanagottapu** [comment]
@SB2318 can you assign me this issue

**Comment by SB2318** [comment]
@jaickeyminj  please let me know your availability for this task.

**Comment by jaickeyminj** [comment]
Hi @SB2318 ,

I am available. Please describe the issue.
Thanks!

**Comment by SB2318** [comment]
> Hi @SB2318 ,
> 
> I am available. Please describe the issue. Thanks!

Okay, but as you raised the issue, please describe yourself,

Currently, there are three **Routes** in the backend.
**(i) userRoute**
**(ii) articleRoute**
 **(iii) specializationRoute**
 
 Now, If you have enough visualization how can you optimize those routes and controllers without losing any features You can start.

**Comment by SB2318** [comment]
evaluate this at a later time.
