### ISSUE TITLE
💡[FEATURE]: Create API for Storing Doctor Specializations.

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#76]
**Is your feature request related to a problem? Please describe.**

Create an API that can store a list of categories of specializations for various doctors. This API will allow users to access and update the list of specializations easily.

**Describe the solution you'd like**

```
Schema:{
    [
     {
      id: string,
      name: string,
      countOfExistingDoctors: number,
      doctor_ids:[ ],
      last_updated_at : date,
      created_at :  date,
      contributed_by: UserData
     }

  ]
}
```
  example :[ "Cardiology", "Dermatology", "Pediatrics"]

**Comment by rushiii3** [comment]
Hey @SB2318, i would like to give a try please assign me this task!

**Comment by SB2318** [comment]
> Hey @SB2318, i would like to give a try please assign me this task!

I have not seen any PR yet.

**Comment by rushiii3** [comment]
Hey @SB2318, I have doubts:
1. `id: string` is it a string like "Cardiology" or a MongoDB object like "664f8078c307087311e5259a"?
2. `contributed_by: UserData` what does UserData refer to?

**Comment by SB2318** [comment]
> Hey @SB2318, I have doubts:
> 
> 1. `id: string` is it a string like "Cardiology" or a MongoDB object like "664f8078c307087311e5259a"?
> 2. `contributed_by: UserData` what does UserData refer to?

I will explain

**Comment by rushiii3** [comment]
Hey @SB2318, kindly update me as soon as possible.

**Comment by SB2318** [comment]
> Hey @SB2318, kindly update me as soon as possible.

id : random id for mongodb object , it is a primary key
UserData :  UserModel object **(./backend/models/UserModel.js)**

**Comment by rushiii3** [comment]
Hey @SB2318, kindly check the PR #99
