### ISSUE TITLE
📝[Docs]: grammatical errors in Readme file

### ISSUE THREAD

**Issue by alishasingh06** [SB2318/UltimateHealth#79]
there are a few grammatical errors that need to be removed from the Readme file

**Comment by alishasingh06** [comment]
resolved in PR #9 please merge the PR and assign levels

**Comment by SB2318** [comment]
@alishasingh06 Please update your branch and make your changes, then please raise a PR.

**Comment by alishasingh06** [comment]
done, kindly merge the PR
