### ISSUE TITLE
💡[FEATURE]: Extension of Auth API :  Email verification for user in backend

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#80]
**Is your feature request related to a problem? Please describe.**

Email verification is an important process that helps ensure the validity and authenticity of an email address provided by a user. 

**Describe the solution you'd like**

After the Registration process is complete, (not login) the user has to verify their mail id, only after that, they can go to the Home page.

**Describe alternatives you've considered**

You can use [nodmailer](https://nodemailer.com/about/).

**Additional context**

Reference:
(i) https://faun.pub/verifying-emails-b95a0c1c3809

**Comment by nishant0708** [comment]
can you assign me this issue under gssoc 24.

**Comment by SB2318** [comment]
@nishant0708 do you want to take this issue?

**Comment by nishant0708** [comment]
Yes

**Comment by Suyash878** [comment]
@SB2318 I would like to work on this issue, I have worked on a similar issue before.

**Comment by SB2318** [comment]
@nishant0708  any update?

**Comment by nishant0708** [comment]
@SB2318  please check pr #92

**Comment by SB2318** [comment]
@nishant0708 please message me on discord.

**Comment by nishant0708** [comment]
What is your discord id?

**Comment by SB2318** [comment]
> What is your discord id?

susmita_

**Comment by nishant0708** [comment]
Niko7479
