### ISSUE TITLE
💡[FEATURE]:  Create ArticleDescriptionScreen

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#84]
Prototype :

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/562468a8-97d0-4981-ae16-139df265bd34)

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/0f5349ef-d6a8-480c-ac40-beb52ff0ccb7)

## Tasks:

This is a parent issue, with the following tasks.

### 1. HumanBodyMap Component: **(Level2)**

 Here first of all you have to integrate one library (react-native-body-highlighter)

Then you have to create a separate component, where we will render the BodyMap, and there will be a dropdown also.

The main purpose is that User can select the related body part (On which they want to share their insights) from the dropdown as well as by touching the bodymap image, that part will highlight, and the selected item of the dropdown automatically set to the dropdown.
As well as when they select the body part from the dropdown, it will be automatically highlighted on the body map.

Users can also move the body to the front and back.
![image](https://github.com/SB2318/UltimateHealth/assets/87614560/7638357f-0b9e-455e-89e2-47538ba2e784)

### 2. BottomSheet Dialog View for Tags. (**Level2**)

   In this part, you will be working on this functionality.
   
You must create a BottomSheet dialog or modal with a list of tags/categories available for articles. Users can select multiple items, and when it closes you have to pass the list of categories to the component, and the List will be displayed as per UI.
   

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/56ae47ec-26f5-436d-b316-44d653d7513c)

### 3. Select Image or capture image from device and display it on the screen (**Level 2**)

You will be responsible for design the following component.

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/b670a302-ebec-422c-b02a-a2ede8c1980e)

Make sure you have added the necessary permission in the AndroidManifest file.

Select Image from the device and display a preview on the screen,
Width and height similar to either descriptionBox or HumanBodyMap image

### 4. Create ArticleDesciption Screen (**Level1**)

Create ArticleDescription Screen, add it to StackNavigation, and Design the screen  as per UI and with above components.

Give Validation also for each field.

**Comment by RamakrushnaBiswal** [comment]
@SB2318 didn't understand the issue

**Comment by anjaliyadavks** [comment]
Hi @SB2318 
Could you please assign the issue to me under GSSOC? I'm eager to drive in and make a meaningful impact. Thank you for considering my request!
