### ISSUE TITLE
💡[FEATURE]:  Login  page Development

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#85]
### Task Description Commit History:

https://github.com/SB2318/UltimateHealth/commit/cacd2fd7dad8e955694b203bc989fefd14cbbfa8

**Your Tasks:**

* Login API integration
* Follow the MVC pattern and create the Model and required classes for calling those APIs.
* Store User Data in local storage
* Integrate it with respective screens
* Validate the email and password.
* Test it with the backend server (Instructions are available at **README** file.) 

### Task Area:

* **LoginScreen** (`./frontend/src/screens/auth/LoginScreen.tsx`)
* **AuthApiService** (`./frontend/src/services/AuthApiService.ts`)

Complete the provided tasks and test with email and password (will be provided).
Please discuss once for more details.
Contact in the respective project channel, or discord id (susmita_5116)

**Comment by iamworrell** [comment]
How long do I have to solve this issue?

**Comment by nishant0708** [comment]
hey i can create this page you can checkout my designs as well 
![Screenshot_1716787783](https://github.com/SB2318/UltimateHealth/assets/101548649/662c876c-1186-42ee-a980-671e4623c9fd)
![Screenshot_1716787804](https://github.com/SB2318/UltimateHealth/assets/101548649/3faa1ee2-4b24-4350-9b6d-c3bdd6c3c87b)

**Comment by Aditijainnn** [comment]
please assign me this task @SB2318

**Comment by SB2318** [comment]
> How long do I have to solve this issue?

Continuation of #61 . Please wait

**Comment by shreyasupe35** [comment]
Hi I would like to work on this issue, please assign me

**Comment by SB2318** [comment]
@iamworrell  Please let me know your availability for this task.

**Comment by iamworrell** [comment]
@iamworrell I am available and ready to work on this task, I would like for you to assign me

**Comment by iamworrell** [comment]
@SB2318  I am available and ready to work on this task, I would like for you to assign me

**Comment by SB2318** [comment]
> How long do I have to solve this issue?

@iamworrell  Thanks for selecting the repository, you can start.

**Comment by SB2318** [comment]
@iamworrell  please give an update.

**Comment by iamworrell** [comment]
@SB2318 actually I thought this was a react project, when I found out this was react-native I had to take time and learn how to set up the environment, I'm just beginning to work on the actual project...If you would like you can assign someone else the task.

**Comment by SB2318** [comment]
> @SB2318 actually I thought this was a react project, when I found out this was react-native I had to take time and learn how to set up the environment, I'm just beginning to work on the actual project...If you would like you can assign someone else the task.

Okay, no problem, Let me know you face any further difficulties, we can sort out together. 😇

**Comment by SB2318** [comment]
> @SB2318 In the tasks list you said to store user data locally, do you mean the user credentials to register and login must be stored locally?

No, from API you get some response as user_details.

**Valid Login**

![valid_login](https://github.com/SB2318/UltimateHealth/assets/83421425/4c8e4e42-0fcf-4e82-934a-11c200890f41)

So, you have to Stringify the  UserData and have to store it locally.

**Comment by iamworrell** [comment]
Still working on the issue, will have something worth showing soon.

**Comment by SB2318** [comment]
> Still working on the issue, will have something worth showing soon.

Sure! Our main goal is to learn something new in tech through this open-source program, And I appreciate your effort 💗.

Let me know if you need any help.

**Comment by iamworrell** [comment]
Im basically finished.. all tasks have been completed just making minor adjustments.

**Comment by iamworrell** [comment]
@SB2318 Im basically finished.. all tasks have been completed just making minor adjustments.

**Comment by iamworrell** [comment]
@SB2318 I made a pull request

**Comment by SB2318** [comment]
> @SB2318 I made a pull request

Okay, will check and get back to you soon. Thanks for your contribution. 💖💖

**Comment by iamworrell** [comment]
@SB2318 I made changes on develop branch and did a pull request

**Comment by iamworrell** [comment]
@SB2318 updated branch and made a new pull request
