### ISSUE TITLE
💡[FEATURE]:  Forgot Password  module Development

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#86]

**Comment by Sakshi007c** [comment]
I would like to work on this issue @SB2318

**Comment by Aditijainnn** [comment]
Can you please assign me his issue @SB2318

**Comment by PriyankaRaskhit** [comment]
Can you assign me this issue @SB2318, I would like to work on this

**Comment by SB2318** [comment]
@Sakshi007c Please let me know your availability for the issue?

**Comment by nishant0708** [comment]
hey @SB2318 is This a backend task . if so  can you  assign it to me..

**Comment by SB2318** [comment]
> hey @SB2318 is This a backend task . if so can you assign it to me..

API integration

**Comment by SB2318** [comment]
@Aditijainnn @PriyankaRaskhit @nishant0708 Please let me know your availabilities for this task.

**Comment by nishant0708** [comment]
Hey @SB2318  I am very little knowledge about native and it is frontend integration that's why it will be too tough for me...

**Comment by SB2318** [comment]
> Hey @SB2318 I am very little knowledge about native and it is frontend integration that's why it will be too tough for me...

Okay

**Comment by SB2318** [comment]
@PriyankaRaskhit please let me know your availability.

**Comment by krishk2** [comment]
Hey, @SB2318 I am interested to contribute to this project and would like to work on this issue. Could you please assign it to me?

**Comment by SB2318** [comment]
> Hey, @SB2318 I am interested to contribute to this project and would like to work on this issue. Could you please assign it to me?

Okay, you can start work from tomorrow. 😇
For any queries, please mail at : **ultimate.health25@gmail.com**

**Comment by SB2318** [comment]
> Hey, @SB2318 I am interested to contribute to this project and would like to work on this issue. Could you please assign it to me?

@krishk2 Thanks for selecting the repository, you can start work. 😊
You have to handle the forgot password action of the login page.
First, please try to run the application. If you need more clarification about your work, please reach out to me.
