### ISSUE TITLE
💡[FEATURE]:  Text Editor Component development

### ISSUE THREAD

**Issue by SB2318** [SB2318/UltimateHealth#87]
![WhatsApp Image 2024-07-08 at 12 43 43 AM](https://github.com/SB2318/UltimateHealth/assets/87614560/6265acd5-07f0-4c94-b382-8b241a014fa6)

**Comment by Shweta-281** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me?

**Comment by Yogesh-ok55** [comment]
Please assign this issue to me , i would love to work on this

**Comment by SB2318** [comment]
@Shweta-281 let me know if you want to work on this issue?

**Comment by Shweta-281** [comment]
@SB2318 Yah, Sure

**Comment by SB2318** [comment]
@Shweta-281 please give an update of your task.

**Comment by SB2318** [comment]
@Yogesh-ok55 are you available for this issue?

**Comment by Yogesh-ok55** [comment]
Yes I am

**Comment by SB2318** [comment]
> when i try to open this by writing npm start i dont know a bunch of things loading and what is happening i dont know please guide how to run this

Please share the screenshot in the discord channel.

**Comment by SB2318** [comment]
@Yogesh-ok55 Please join in the VC

**Comment by SB2318** [comment]
@Yogesh-ok55 please give a quick update about your task.
