### ISSUE TITLE
📝[Docs]:   Enhance Readme.md with Animated Emojis, Alignment Fixes, Project Snapshots, and Contributor Profile Pictures.

### ISSUE THREAD

**Issue by Aditijainnn** [SB2318/UltimateHealth#90]
Readme.md file is good currently but it can be more fascinating by adding animated emojis , fixing allignment , adding snapshots of our project, dsiplaying pfp of contributors in contri section and many more updates

@SB2318  assign this issue to me I will update it
I am working under gssoc24

@Aditijainnn 
Please report

**Comment by SB2318** [comment]
@Aditijainnn I will send you the contributors list.

Also add  Project Participation section.

![project-participation](https://github.com/SB2318/UltimateHealth/assets/87614560/e0aa7eaa-c95d-4bc1-967b-20e11f82fe63)

**Comment by Aditijainnn** [comment]
Okay please  send me the contributors list

**Comment by SB2318** [comment]
@Aditijainnn Please share your display name as per **GSSOC** server.

**Comment by SB2318** [comment]
> > @Aditijainnn Please share your display name as per **GSSOC** server.
> > Ig the readme file got updated

No, 
* With Headers, you can add an animated emoji or something like a dropdown.

  For your reference:
  https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61

* In the contributor sections, not all contributors are present, although currently, we are using a specific URL, but it is only collecting contributors of the main branch.

So, you can work on those parts also, If you want then let me know.

**Comment by Aditijainnn** [comment]
> > > @Aditijainnn Please share your display name as per **GSSOC** server.
> > > Ig the readme file got updated
> 
> No,
> 
>     * With Headers, you can add an animated emoji or something like a dropdown.
>       For your reference:
>       https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61
> 
>     * In the contributor sections, not all contributors are present, although currently, we are using a specific URL, but it is only collecting contributors of the main branch.
> 
> 
> So, you can work on those parts also, If you want then let me know.

okay sure I'll work on it

**Comment by SB2318** [comment]
> > > > @Aditijainnn Please share your display name as per **GSSOC** server.
> > > > Ig the readme file got updated
> > 
> > 
> > No,
> > ```
> > * With Headers, you can add an animated emoji or something like a dropdown.
> >   For your reference:
> >   https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61
> > 
> > * In the contributor sections, not all contributors are present, although currently, we are using a specific URL, but it is only collecting contributors of the main branch.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, you can work on those parts also, If you want then let me know.
> 
> okay sure I'll work on it

You can ask me in the project channel if anything is required.

**Comment by Aditijainnn** [comment]
@SB2318 you can check and please accept my pr
