### ISSUE TITLE
📝[Docs]: Enhancement: Add Links to Headers in README File

### ISSUE THREAD

**Issue by MaryamMohamedYahya** [SB2318/UltimateHealth#94]
Currently, the README file lacks links in the headers, making it difficult for users to navigate through the content. This enhancement aims to improve the user experience by adding clickable links to the headers, such as "Getting Started" or other relevant sections. By doing so, users will be able to quickly jump to specific sections of the README file, saving time and effort. This enhancement will make the README file more user-friendly and enhance its overall readability.

### Headers

![image](https://github.com/SB2318/UltimateHealth/assets/87614560/a0b1d50c-78d2-4d7c-8355-9663c4426b38)

@MaryamMohamedYahya  Please check the image as well as README file. (Work on **main** branch)

**Comment by SB2318** [comment]
@MaryamMohamedYahya let me know do you want to take this issue?

**Comment by MaryamMohamedYahya** [comment]
Sure!

**Comment by shreyasupe35** [comment]
Hi ,I would like to work on this issue, please assign me

**Comment by SB2318** [comment]
@MaryamMohamedYahya Please share your display name on the server.

**Comment by MaryamMohamedYahya** [comment]
> @MaryamMohamedYahya Please share your display name as per GSSOC server.

Maryam Mohamed | Contributor
