### ISSUE TITLE
💡[FEATURE]: Delete user account from backend

### ISSUE THREAD

**Issue by Kamaleshbala01** [SB2318/UltimateHealth#97]
Create an API for deleting user details from the database.

Do you want to work on it @Kamaleshbala01  under **GSSOC**?

**Comment by SB2318** [comment]
No, It is already dynamic. Please check out the working branch.

**Comment by Kamaleshbala01** [comment]
Yes I do

**Comment by Kamaleshbala01** [comment]
@SB2318  I created a PR for this Feature

**Comment by Kamaleshbala01** [comment]
@SB2318  How long it take to merge my PR .

**Comment by SB2318** [comment]
today
