### ISSUE TITLE
📝[Docs]: Add Instructions for Forking and cloning the Project on GitHub. (Create another md file)

### ISSUE THREAD

**Issue by Sibam-Paul** [SB2318/UltimateHealth#98]
From beginner perspective, we would like to integrate a readme file that provides instructions for contributors on how to create a fork of the **default branch**, the **entire project**, or a **specific branch.** This will help contributors understand the process better.

**Comment by SB2318** [comment]
Don't consider this as a small issue , this little contributions can help many contributors, Again If anyone think it is,  then I posted this issue on my  responsibility.  @Sibam-Paul  do you want to take this?

**Comment by Sibam-Paul** [comment]
@SB2318 Why not it's really an important issue to be solved foremost...

**Comment by Sibam-Paul** [comment]
@Just wanna ask should I work on main or develop branch only to include a learning,md file

**Comment by Sibam-Paul** [comment]
@SB2318 It would be better u write in Contributing.md without creating another md file 
I can include here 
![image](https://github.com/SB2318/UltimateHealth/assets/158052549/5d0373c1-12a6-4f74-8b8e-3625514564d4)

Doing changes

**Comment by Sibam-Paul** [comment]
@SB2318 please review my PR
